/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DbConnectionUri } from '../models';
// @ts-ignore
import type { DbCreateProject201Response } from '../models';
// @ts-ignore
import type { DbCreateProjectRequest } from '../models';
// @ts-ignore
import type { DbError } from '../models';
// @ts-ignore
import type { DbGetProject200Response } from '../models';
// @ts-ignore
import type { DbListProjects200Response } from '../models';
// @ts-ignore
import type { DbUpdateProjectRequest } from '../models';
/**
 * DbProjectsApi - axios parameter creator
 * @export
 */
export const DbProjectsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create project
         * @param {DbCreateProjectRequest} dbCreateProjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbCreateProject: async (dbCreateProjectRequest: DbCreateProjectRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dbCreateProjectRequest' is not null or undefined
            assertParamExists('dbCreateProject', 'dbCreateProjectRequest', dbCreateProjectRequest)
            const localVarPath = `/v1/db/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dbCreateProjectRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete project
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbDeleteProject: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('dbDeleteProject', 'id', id)
            const localVarPath = `/v1/db/projects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get connection URI
         * @param {string} id 
         * @param {string} roleName 
         * @param {string} [branchId] 
         * @param {string} [endpointId] 
         * @param {string} [databaseName] 
         * @param {boolean} [pooled] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbGetConnectionUri: async (id: string, roleName: string, branchId?: string, endpointId?: string, databaseName?: string, pooled?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('dbGetConnectionUri', 'id', id)
            // verify required parameter 'roleName' is not null or undefined
            assertParamExists('dbGetConnectionUri', 'roleName', roleName)
            const localVarPath = `/v1/db/projects/{id}/connection_uri`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (branchId !== undefined) {
                localVarQueryParameter['branch_id'] = branchId;
            }

            if (endpointId !== undefined) {
                localVarQueryParameter['endpoint_id'] = endpointId;
            }

            if (databaseName !== undefined) {
                localVarQueryParameter['database_name'] = databaseName;
            }

            if (roleName !== undefined) {
                localVarQueryParameter['role_name'] = roleName;
            }

            if (pooled !== undefined) {
                localVarQueryParameter['pooled'] = pooled;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get project
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbGetProject: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('dbGetProject', 'id', id)
            const localVarPath = `/v1/db/projects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List projects
         * @param {string} [cursor] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbListProjects: async (cursor?: string, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/db/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update project
         * @param {string} id 
         * @param {DbUpdateProjectRequest} dbUpdateProjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbUpdateProject: async (id: string, dbUpdateProjectRequest: DbUpdateProjectRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('dbUpdateProject', 'id', id)
            // verify required parameter 'dbUpdateProjectRequest' is not null or undefined
            assertParamExists('dbUpdateProject', 'dbUpdateProjectRequest', dbUpdateProjectRequest)
            const localVarPath = `/v1/db/projects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dbUpdateProjectRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DbProjectsApi - functional programming interface
 * @export
 */
export const DbProjectsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DbProjectsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create project
         * @param {DbCreateProjectRequest} dbCreateProjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dbCreateProject(dbCreateProjectRequest: DbCreateProjectRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DbCreateProject201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dbCreateProject(dbCreateProjectRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DbProjectsApi.dbCreateProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete project
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dbDeleteProject(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DbGetProject200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dbDeleteProject(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DbProjectsApi.dbDeleteProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get connection URI
         * @param {string} id 
         * @param {string} roleName 
         * @param {string} [branchId] 
         * @param {string} [endpointId] 
         * @param {string} [databaseName] 
         * @param {boolean} [pooled] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dbGetConnectionUri(id: string, roleName: string, branchId?: string, endpointId?: string, databaseName?: string, pooled?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DbConnectionUri>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dbGetConnectionUri(id, roleName, branchId, endpointId, databaseName, pooled, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DbProjectsApi.dbGetConnectionUri']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get project
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dbGetProject(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DbGetProject200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dbGetProject(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DbProjectsApi.dbGetProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List projects
         * @param {string} [cursor] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dbListProjects(cursor?: string, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DbListProjects200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dbListProjects(cursor, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DbProjectsApi.dbListProjects']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update project
         * @param {string} id 
         * @param {DbUpdateProjectRequest} dbUpdateProjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dbUpdateProject(id: string, dbUpdateProjectRequest: DbUpdateProjectRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DbGetProject200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dbUpdateProject(id, dbUpdateProjectRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DbProjectsApi.dbUpdateProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DbProjectsApi - factory interface
 * @export
 */
export const DbProjectsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DbProjectsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create project
         * @param {DbProjectsApiDbCreateProjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbCreateProject(requestParameters: DbProjectsApiDbCreateProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<DbCreateProject201Response> {
            return localVarFp.dbCreateProject(requestParameters.dbCreateProjectRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete project
         * @param {DbProjectsApiDbDeleteProjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbDeleteProject(requestParameters: DbProjectsApiDbDeleteProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<DbGetProject200Response> {
            return localVarFp.dbDeleteProject(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get connection URI
         * @param {DbProjectsApiDbGetConnectionUriRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbGetConnectionUri(requestParameters: DbProjectsApiDbGetConnectionUriRequest, options?: RawAxiosRequestConfig): AxiosPromise<DbConnectionUri> {
            return localVarFp.dbGetConnectionUri(requestParameters.id, requestParameters.roleName, requestParameters.branchId, requestParameters.endpointId, requestParameters.databaseName, requestParameters.pooled, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get project
         * @param {DbProjectsApiDbGetProjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbGetProject(requestParameters: DbProjectsApiDbGetProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<DbGetProject200Response> {
            return localVarFp.dbGetProject(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List projects
         * @param {DbProjectsApiDbListProjectsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbListProjects(requestParameters: DbProjectsApiDbListProjectsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<DbListProjects200Response> {
            return localVarFp.dbListProjects(requestParameters.cursor, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update project
         * @param {DbProjectsApiDbUpdateProjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dbUpdateProject(requestParameters: DbProjectsApiDbUpdateProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<DbGetProject200Response> {
            return localVarFp.dbUpdateProject(requestParameters.id, requestParameters.dbUpdateProjectRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for dbCreateProject operation in DbProjectsApi.
 * @export
 * @interface DbProjectsApiDbCreateProjectRequest
 */
export interface DbProjectsApiDbCreateProjectRequest {
    /**
     * 
     * @type {DbCreateProjectRequest}
     * @memberof DbProjectsApiDbCreateProject
     */
    readonly dbCreateProjectRequest: DbCreateProjectRequest
}

/**
 * Request parameters for dbDeleteProject operation in DbProjectsApi.
 * @export
 * @interface DbProjectsApiDbDeleteProjectRequest
 */
export interface DbProjectsApiDbDeleteProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof DbProjectsApiDbDeleteProject
     */
    readonly id: string
}

/**
 * Request parameters for dbGetConnectionUri operation in DbProjectsApi.
 * @export
 * @interface DbProjectsApiDbGetConnectionUriRequest
 */
export interface DbProjectsApiDbGetConnectionUriRequest {
    /**
     * 
     * @type {string}
     * @memberof DbProjectsApiDbGetConnectionUri
     */
    readonly id: string

    /**
     * 
     * @type {string}
     * @memberof DbProjectsApiDbGetConnectionUri
     */
    readonly roleName: string

    /**
     * 
     * @type {string}
     * @memberof DbProjectsApiDbGetConnectionUri
     */
    readonly branchId?: string

    /**
     * 
     * @type {string}
     * @memberof DbProjectsApiDbGetConnectionUri
     */
    readonly endpointId?: string

    /**
     * 
     * @type {string}
     * @memberof DbProjectsApiDbGetConnectionUri
     */
    readonly databaseName?: string

    /**
     * 
     * @type {boolean}
     * @memberof DbProjectsApiDbGetConnectionUri
     */
    readonly pooled?: boolean
}

/**
 * Request parameters for dbGetProject operation in DbProjectsApi.
 * @export
 * @interface DbProjectsApiDbGetProjectRequest
 */
export interface DbProjectsApiDbGetProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof DbProjectsApiDbGetProject
     */
    readonly id: string
}

/**
 * Request parameters for dbListProjects operation in DbProjectsApi.
 * @export
 * @interface DbProjectsApiDbListProjectsRequest
 */
export interface DbProjectsApiDbListProjectsRequest {
    /**
     * 
     * @type {string}
     * @memberof DbProjectsApiDbListProjects
     */
    readonly cursor?: string

    /**
     * 
     * @type {number}
     * @memberof DbProjectsApiDbListProjects
     */
    readonly limit?: number
}

/**
 * Request parameters for dbUpdateProject operation in DbProjectsApi.
 * @export
 * @interface DbProjectsApiDbUpdateProjectRequest
 */
export interface DbProjectsApiDbUpdateProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof DbProjectsApiDbUpdateProject
     */
    readonly id: string

    /**
     * 
     * @type {DbUpdateProjectRequest}
     * @memberof DbProjectsApiDbUpdateProject
     */
    readonly dbUpdateProjectRequest: DbUpdateProjectRequest
}

/**
 * DbProjectsApi - object-oriented interface
 * @export
 * @class DbProjectsApi
 * @extends {BaseAPI}
 */
export class DbProjectsApi extends BaseAPI {
    /**
     * 
     * @summary Create project
     * @param {DbProjectsApiDbCreateProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DbProjectsApi
     */
    public dbCreateProject(requestParameters: DbProjectsApiDbCreateProjectRequest, options?: RawAxiosRequestConfig) {
        return DbProjectsApiFp(this.configuration).dbCreateProject(requestParameters.dbCreateProjectRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete project
     * @param {DbProjectsApiDbDeleteProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DbProjectsApi
     */
    public dbDeleteProject(requestParameters: DbProjectsApiDbDeleteProjectRequest, options?: RawAxiosRequestConfig) {
        return DbProjectsApiFp(this.configuration).dbDeleteProject(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get connection URI
     * @param {DbProjectsApiDbGetConnectionUriRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DbProjectsApi
     */
    public dbGetConnectionUri(requestParameters: DbProjectsApiDbGetConnectionUriRequest, options?: RawAxiosRequestConfig) {
        return DbProjectsApiFp(this.configuration).dbGetConnectionUri(requestParameters.id, requestParameters.roleName, requestParameters.branchId, requestParameters.endpointId, requestParameters.databaseName, requestParameters.pooled, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get project
     * @param {DbProjectsApiDbGetProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DbProjectsApi
     */
    public dbGetProject(requestParameters: DbProjectsApiDbGetProjectRequest, options?: RawAxiosRequestConfig) {
        return DbProjectsApiFp(this.configuration).dbGetProject(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List projects
     * @param {DbProjectsApiDbListProjectsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DbProjectsApi
     */
    public dbListProjects(requestParameters: DbProjectsApiDbListProjectsRequest = {}, options?: RawAxiosRequestConfig) {
        return DbProjectsApiFp(this.configuration).dbListProjects(requestParameters.cursor, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update project
     * @param {DbProjectsApiDbUpdateProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DbProjectsApi
     */
    public dbUpdateProject(requestParameters: DbProjectsApiDbUpdateProjectRequest, options?: RawAxiosRequestConfig) {
        return DbProjectsApiFp(this.configuration).dbUpdateProject(requestParameters.id, requestParameters.dbUpdateProjectRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

