/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * DnsApi - axios parameter creator
 * @export
 */
export const DnsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Removes a DNS zone or record from the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Delete a DNS zone or record
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteV1DnsByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('deleteV1DnsByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/dns/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Reads DNS state — a zone, a record, a listing — from the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Read your org\'s DNS zones and records
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1DnsByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('getV1DnsByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/dns/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Published because this address accepts every method, but the DNS surface routes nothing here: no zone or record is read or changed. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Not served by the DNS surface
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        optionsV1DnsByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('optionsV1DnsByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/dns/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'OPTIONS', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Amends a DNS zone or record on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Amend a DNS zone or record
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchV1DnsByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('patchV1DnsByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/dns/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates DNS state — a zone, a record — on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Create a DNS zone or record
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1DnsByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('postV1DnsByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/dns/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Replaces a DNS zone or record on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Replace a DNS zone or record
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putV1DnsByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('putV1DnsByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/dns/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Published because this address accepts every method, but the DNS surface routes nothing here: no zone or record is read or changed. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Not served by the DNS surface
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        traceV1DnsByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('traceV1DnsByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/dns/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'TRACE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DnsApi - functional programming interface
 * @export
 */
export const DnsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DnsApiAxiosParamCreator(configuration)
    return {
        /**
         * Removes a DNS zone or record from the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Delete a DNS zone or record
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteV1DnsByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteV1DnsByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DnsApi.deleteV1DnsByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Reads DNS state — a zone, a record, a listing — from the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Read your org\'s DNS zones and records
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1DnsByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getV1DnsByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DnsApi.getV1DnsByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Published because this address accepts every method, but the DNS surface routes nothing here: no zone or record is read or changed. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Not served by the DNS surface
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async optionsV1DnsByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.optionsV1DnsByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DnsApi.optionsV1DnsByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Amends a DNS zone or record on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Amend a DNS zone or record
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchV1DnsByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchV1DnsByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DnsApi.patchV1DnsByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates DNS state — a zone, a record — on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Create a DNS zone or record
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postV1DnsByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postV1DnsByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DnsApi.postV1DnsByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Replaces a DNS zone or record on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Replace a DNS zone or record
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putV1DnsByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putV1DnsByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DnsApi.putV1DnsByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Published because this address accepts every method, but the DNS surface routes nothing here: no zone or record is read or changed. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Not served by the DNS surface
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async traceV1DnsByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.traceV1DnsByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DnsApi.traceV1DnsByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DnsApi - factory interface
 * @export
 */
export const DnsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DnsApiFp(configuration)
    return {
        /**
         * Removes a DNS zone or record from the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Delete a DNS zone or record
         * @param {DnsApiDeleteV1DnsByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteV1DnsByWildcard1(requestParameters: DnsApiDeleteV1DnsByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * Reads DNS state — a zone, a record, a listing — from the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Read your org\'s DNS zones and records
         * @param {DnsApiGetV1DnsByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1DnsByWildcard1(requestParameters: DnsApiGetV1DnsByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * Published because this address accepts every method, but the DNS surface routes nothing here: no zone or record is read or changed. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Not served by the DNS surface
         * @param {DnsApiOptionsV1DnsByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        optionsV1DnsByWildcard1(requestParameters: DnsApiOptionsV1DnsByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.optionsV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * Amends a DNS zone or record on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Amend a DNS zone or record
         * @param {DnsApiPatchV1DnsByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchV1DnsByWildcard1(requestParameters: DnsApiPatchV1DnsByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.patchV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates DNS state — a zone, a record — on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Create a DNS zone or record
         * @param {DnsApiPostV1DnsByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1DnsByWildcard1(requestParameters: DnsApiPostV1DnsByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * Replaces a DNS zone or record on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Replace a DNS zone or record
         * @param {DnsApiPutV1DnsByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putV1DnsByWildcard1(requestParameters: DnsApiPutV1DnsByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.putV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * Published because this address accepts every method, but the DNS surface routes nothing here: no zone or record is read or changed. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
         * @summary Not served by the DNS surface
         * @param {DnsApiTraceV1DnsByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        traceV1DnsByWildcard1(requestParameters: DnsApiTraceV1DnsByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.traceV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteV1DnsByWildcard1 operation in DnsApi.
 * @export
 * @interface DnsApiDeleteV1DnsByWildcard1Request
 */
export interface DnsApiDeleteV1DnsByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof DnsApiDeleteV1DnsByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for getV1DnsByWildcard1 operation in DnsApi.
 * @export
 * @interface DnsApiGetV1DnsByWildcard1Request
 */
export interface DnsApiGetV1DnsByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof DnsApiGetV1DnsByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for optionsV1DnsByWildcard1 operation in DnsApi.
 * @export
 * @interface DnsApiOptionsV1DnsByWildcard1Request
 */
export interface DnsApiOptionsV1DnsByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof DnsApiOptionsV1DnsByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for patchV1DnsByWildcard1 operation in DnsApi.
 * @export
 * @interface DnsApiPatchV1DnsByWildcard1Request
 */
export interface DnsApiPatchV1DnsByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof DnsApiPatchV1DnsByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for postV1DnsByWildcard1 operation in DnsApi.
 * @export
 * @interface DnsApiPostV1DnsByWildcard1Request
 */
export interface DnsApiPostV1DnsByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof DnsApiPostV1DnsByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for putV1DnsByWildcard1 operation in DnsApi.
 * @export
 * @interface DnsApiPutV1DnsByWildcard1Request
 */
export interface DnsApiPutV1DnsByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof DnsApiPutV1DnsByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for traceV1DnsByWildcard1 operation in DnsApi.
 * @export
 * @interface DnsApiTraceV1DnsByWildcard1Request
 */
export interface DnsApiTraceV1DnsByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof DnsApiTraceV1DnsByWildcard1
     */
    readonly wildcard1: string
}

/**
 * DnsApi - object-oriented interface
 * @export
 * @class DnsApi
 * @extends {BaseAPI}
 */
export class DnsApi extends BaseAPI {
    /**
     * Removes a DNS zone or record from the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
     * @summary Delete a DNS zone or record
     * @param {DnsApiDeleteV1DnsByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DnsApi
     */
    public deleteV1DnsByWildcard1(requestParameters: DnsApiDeleteV1DnsByWildcard1Request, options?: RawAxiosRequestConfig) {
        return DnsApiFp(this.configuration).deleteV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Reads DNS state — a zone, a record, a listing — from the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
     * @summary Read your org\'s DNS zones and records
     * @param {DnsApiGetV1DnsByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DnsApi
     */
    public getV1DnsByWildcard1(requestParameters: DnsApiGetV1DnsByWildcard1Request, options?: RawAxiosRequestConfig) {
        return DnsApiFp(this.configuration).getV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Published because this address accepts every method, but the DNS surface routes nothing here: no zone or record is read or changed. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
     * @summary Not served by the DNS surface
     * @param {DnsApiOptionsV1DnsByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DnsApi
     */
    public optionsV1DnsByWildcard1(requestParameters: DnsApiOptionsV1DnsByWildcard1Request, options?: RawAxiosRequestConfig) {
        return DnsApiFp(this.configuration).optionsV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Amends a DNS zone or record on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
     * @summary Amend a DNS zone or record
     * @param {DnsApiPatchV1DnsByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DnsApi
     */
    public patchV1DnsByWildcard1(requestParameters: DnsApiPatchV1DnsByWildcard1Request, options?: RawAxiosRequestConfig) {
        return DnsApiFp(this.configuration).patchV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates DNS state — a zone, a record — on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
     * @summary Create a DNS zone or record
     * @param {DnsApiPostV1DnsByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DnsApi
     */
    public postV1DnsByWildcard1(requestParameters: DnsApiPostV1DnsByWildcard1Request, options?: RawAxiosRequestConfig) {
        return DnsApiFp(this.configuration).postV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Replaces a DNS zone or record on the Hanzo DNS control plane. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
     * @summary Replace a DNS zone or record
     * @param {DnsApiPutV1DnsByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DnsApi
     */
    public putV1DnsByWildcard1(requestParameters: DnsApiPutV1DnsByWildcard1Request, options?: RawAxiosRequestConfig) {
        return DnsApiFp(this.configuration).putV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Published because this address accepts every method, but the DNS surface routes nothing here: no zone or record is read or changed. The plane owns the authoritative zone and record store behind every name pointed at Hanzo; this head keeps none of it. The sub-path after /v1/dns and the query string ARE the plane\'s own API address, relayed verbatim, and the plane\'s answer comes back unchanged — its status code, its Content-Type, and its Location on a redirect this head never follows.  It travels under the CALLER\'S OWN identity and substitutes no service credential, which would collapse tenants: the caller\'s validated session bearer goes upstream as Authorization and the server-validated org as X-Org-Id, so a caller in one org reaches only that org\'s zones, exactly as if it had called the plane directly. The upstream host comes only from deployment config, never from the request, so no path can re-target another host.  Fails closed before a byte leaves cloud: no validated principal is 403; an API key is 401, because a pk-/sk- key is not a JWT the OIDC-gated plane can validate and there is no substitute credential to send in its place; a path that normalizes outside /v1/dns, or still carries a percent-escape or a `..` after one decode, is 400; an unconfigured plane is 503 and an unreachable one 502.
     * @summary Not served by the DNS surface
     * @param {DnsApiTraceV1DnsByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DnsApi
     */
    public traceV1DnsByWildcard1(requestParameters: DnsApiTraceV1DnsByWildcard1Request, options?: RawAxiosRequestConfig) {
        return DnsApiFp(this.configuration).traceV1DnsByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }
}

