/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud\'s own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ExecExecRequest } from '../models';
// @ts-ignore
import type { ExecExecResult } from '../models';
// @ts-ignore
import type { InlineObject } from '../models';
/**
 * ExecApi - axios parameter creator
 * @export
 */
export const ExecApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudDeleteV1Exec: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/exec`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudDeleteV1ExecByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('cloudDeleteV1ExecByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/exec/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1Exec: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/exec`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1ExecByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('cloudGetV1ExecByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/exec/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudOptionsV1Exec: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/exec`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'OPTIONS', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudOptionsV1ExecByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('cloudOptionsV1ExecByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/exec/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'OPTIONS', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPatchV1Exec: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/exec`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPatchV1ExecByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('cloudPatchV1ExecByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/exec/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPostV1Exec: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/exec`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPostV1ExecByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('cloudPostV1ExecByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/exec/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPutV1Exec: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/exec`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPutV1ExecByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('cloudPutV1ExecByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/exec/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudTraceV1Exec: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/exec`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'TRACE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudTraceV1ExecByWildcard1: async (wildcard1: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wildcard1' is not null or undefined
            assertParamExists('cloudTraceV1ExecByWildcard1', 'wildcard1', wildcard1)
            const localVarPath = `/v1/exec/{wildcard1}`
                .replace(`{${"wildcard1"}}`, encodeURIComponent(String(wildcard1)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'TRACE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Programmatic code execution (sibling of /v1/exec, same executor contract)
         * @param {ExecExecRequest} execExecRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        execExecProgrammatic: async (execExecRequest: ExecExecRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'execExecRequest' is not null or undefined
            assertParamExists('execExecProgrammatic', 'execExecRequest', execExecRequest)
            const localVarPath = `/v1/exec/programmatic`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(execExecRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExecApi - functional programming interface
 * @export
 */
export const ExecApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExecApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudDeleteV1Exec(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudDeleteV1Exec(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudDeleteV1Exec']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudDeleteV1ExecByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudDeleteV1ExecByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudDeleteV1ExecByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudGetV1Exec(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudGetV1Exec(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudGetV1Exec']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudGetV1ExecByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudGetV1ExecByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudGetV1ExecByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudOptionsV1Exec(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudOptionsV1Exec(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudOptionsV1Exec']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudOptionsV1ExecByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudOptionsV1ExecByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudOptionsV1ExecByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudPatchV1Exec(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudPatchV1Exec(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudPatchV1Exec']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudPatchV1ExecByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudPatchV1ExecByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudPatchV1ExecByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudPostV1Exec(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudPostV1Exec(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudPostV1Exec']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudPostV1ExecByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudPostV1ExecByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudPostV1ExecByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudPutV1Exec(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudPutV1Exec(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudPutV1Exec']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudPutV1ExecByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudPutV1ExecByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudPutV1ExecByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudTraceV1Exec(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudTraceV1Exec(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudTraceV1Exec']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} wildcard1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudTraceV1ExecByWildcard1(wildcard1: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudTraceV1ExecByWildcard1(wildcard1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.cloudTraceV1ExecByWildcard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Programmatic code execution (sibling of /v1/exec, same executor contract)
         * @param {ExecExecRequest} execExecRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async execExecProgrammatic(execExecRequest: ExecExecRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExecExecResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.execExecProgrammatic(execExecRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExecApi.execExecProgrammatic']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExecApi - factory interface
 * @export
 */
export const ExecApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExecApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudDeleteV1Exec(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudDeleteV1Exec(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExecApiCloudDeleteV1ExecByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudDeleteV1ExecByWildcard1(requestParameters: ExecApiCloudDeleteV1ExecByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudDeleteV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1Exec(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudGetV1Exec(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExecApiCloudGetV1ExecByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1ExecByWildcard1(requestParameters: ExecApiCloudGetV1ExecByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudGetV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudOptionsV1Exec(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudOptionsV1Exec(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExecApiCloudOptionsV1ExecByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudOptionsV1ExecByWildcard1(requestParameters: ExecApiCloudOptionsV1ExecByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudOptionsV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPatchV1Exec(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudPatchV1Exec(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExecApiCloudPatchV1ExecByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPatchV1ExecByWildcard1(requestParameters: ExecApiCloudPatchV1ExecByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudPatchV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPostV1Exec(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudPostV1Exec(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExecApiCloudPostV1ExecByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPostV1ExecByWildcard1(requestParameters: ExecApiCloudPostV1ExecByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudPostV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPutV1Exec(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudPutV1Exec(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExecApiCloudPutV1ExecByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPutV1ExecByWildcard1(requestParameters: ExecApiCloudPutV1ExecByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudPutV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudTraceV1Exec(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudTraceV1Exec(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExecApiCloudTraceV1ExecByWildcard1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudTraceV1ExecByWildcard1(requestParameters: ExecApiCloudTraceV1ExecByWildcard1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudTraceV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Programmatic code execution (sibling of /v1/exec, same executor contract)
         * @param {ExecApiExecExecProgrammaticRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        execExecProgrammatic(requestParameters: ExecApiExecExecProgrammaticRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExecExecResult> {
            return localVarFp.execExecProgrammatic(requestParameters.execExecRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for cloudDeleteV1ExecByWildcard1 operation in ExecApi.
 * @export
 * @interface ExecApiCloudDeleteV1ExecByWildcard1Request
 */
export interface ExecApiCloudDeleteV1ExecByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof ExecApiCloudDeleteV1ExecByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for cloudGetV1ExecByWildcard1 operation in ExecApi.
 * @export
 * @interface ExecApiCloudGetV1ExecByWildcard1Request
 */
export interface ExecApiCloudGetV1ExecByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof ExecApiCloudGetV1ExecByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for cloudOptionsV1ExecByWildcard1 operation in ExecApi.
 * @export
 * @interface ExecApiCloudOptionsV1ExecByWildcard1Request
 */
export interface ExecApiCloudOptionsV1ExecByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof ExecApiCloudOptionsV1ExecByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for cloudPatchV1ExecByWildcard1 operation in ExecApi.
 * @export
 * @interface ExecApiCloudPatchV1ExecByWildcard1Request
 */
export interface ExecApiCloudPatchV1ExecByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof ExecApiCloudPatchV1ExecByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for cloudPostV1ExecByWildcard1 operation in ExecApi.
 * @export
 * @interface ExecApiCloudPostV1ExecByWildcard1Request
 */
export interface ExecApiCloudPostV1ExecByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof ExecApiCloudPostV1ExecByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for cloudPutV1ExecByWildcard1 operation in ExecApi.
 * @export
 * @interface ExecApiCloudPutV1ExecByWildcard1Request
 */
export interface ExecApiCloudPutV1ExecByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof ExecApiCloudPutV1ExecByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for cloudTraceV1ExecByWildcard1 operation in ExecApi.
 * @export
 * @interface ExecApiCloudTraceV1ExecByWildcard1Request
 */
export interface ExecApiCloudTraceV1ExecByWildcard1Request {
    /**
     * 
     * @type {string}
     * @memberof ExecApiCloudTraceV1ExecByWildcard1
     */
    readonly wildcard1: string
}

/**
 * Request parameters for execExecProgrammatic operation in ExecApi.
 * @export
 * @interface ExecApiExecExecProgrammaticRequest
 */
export interface ExecApiExecExecProgrammaticRequest {
    /**
     * 
     * @type {ExecExecRequest}
     * @memberof ExecApiExecExecProgrammatic
     */
    readonly execExecRequest: ExecExecRequest
}

/**
 * ExecApi - object-oriented interface
 * @export
 * @class ExecApi
 * @extends {BaseAPI}
 */
export class ExecApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudDeleteV1Exec(options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudDeleteV1Exec(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExecApiCloudDeleteV1ExecByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudDeleteV1ExecByWildcard1(requestParameters: ExecApiCloudDeleteV1ExecByWildcard1Request, options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudDeleteV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudGetV1Exec(options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudGetV1Exec(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExecApiCloudGetV1ExecByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudGetV1ExecByWildcard1(requestParameters: ExecApiCloudGetV1ExecByWildcard1Request, options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudGetV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudOptionsV1Exec(options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudOptionsV1Exec(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExecApiCloudOptionsV1ExecByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudOptionsV1ExecByWildcard1(requestParameters: ExecApiCloudOptionsV1ExecByWildcard1Request, options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudOptionsV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudPatchV1Exec(options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudPatchV1Exec(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExecApiCloudPatchV1ExecByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudPatchV1ExecByWildcard1(requestParameters: ExecApiCloudPatchV1ExecByWildcard1Request, options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudPatchV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudPostV1Exec(options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudPostV1Exec(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExecApiCloudPostV1ExecByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudPostV1ExecByWildcard1(requestParameters: ExecApiCloudPostV1ExecByWildcard1Request, options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudPostV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudPutV1Exec(options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudPutV1Exec(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExecApiCloudPutV1ExecByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudPutV1ExecByWildcard1(requestParameters: ExecApiCloudPutV1ExecByWildcard1Request, options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudPutV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudTraceV1Exec(options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudTraceV1Exec(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ExecApiCloudTraceV1ExecByWildcard1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public cloudTraceV1ExecByWildcard1(requestParameters: ExecApiCloudTraceV1ExecByWildcard1Request, options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).cloudTraceV1ExecByWildcard1(requestParameters.wildcard1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Programmatic code execution (sibling of /v1/exec, same executor contract)
     * @param {ExecApiExecExecProgrammaticRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecApi
     */
    public execExecProgrammatic(requestParameters: ExecApiExecExecProgrammaticRequest, options?: RawAxiosRequestConfig) {
        return ExecApiFp(this.configuration).execExecProgrammatic(requestParameters.execExecRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

