/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { KmsConfig } from '../models';
// @ts-ignore
import type { KmsHealth } from '../models';
// @ts-ignore
import type { KmsLogin } from '../models';
// @ts-ignore
import type { KmsPut } from '../models';
// @ts-ignore
import type { KmsSecrets } from '../models';
// @ts-ignore
import type { KmsStored } from '../models';
// @ts-ignore
import type { KmsToken } from '../models';
/**
 * KmsApi - axios parameter creator
 * @export
 */
export const KmsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the runtime configuration for the KMS console.  What the console needs before anyone has signed in: the brand, the OIDC issuer it authenticates against, the API base for this subsystem and the path of the login exchange.  Public on purpose, and it holds nothing sensitive — it is deliberately kept under this subsystem\'s own namespace rather than under an admin prefix, so a gateway that admin-gates the admin routes cannot break the console\'s legitimate pre-login fetch.
         * @summary Returns the runtime configuration for the KMS console.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKmsConfig: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/kms/config`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Reports whether this broker can actually serve secrets.  A real readiness probe, not a liveness stub: 200 only when the store is open AND a master key is configured, with `signing` reporting whether signing keys are set up too. Anything less answers 503 with `ready:false` and the reason — no in-process store, or no master key — which are exactly the two states in which the secret operations refuse.  Not token-gated, because the platform must be able to probe it without a credential. It reports the broker\'s configuration state only; no secret, no key material and no tenant name appears in it.
         * @summary Reports whether this broker can actually serve secrets.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKmsHealth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/kms/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lists the secrets your org holds, without their values.  Returns the METADATA of the caller\'s own secrets: each one\'s name, path, environment and sealing scheme. No value and no ciphertext is included — this operation exists to enumerate what is held, and reading a value is a separate, per-secret call.  Scoped to the caller\'s own org and nothing else, structurally: there is no org in the path, the store root is derived from the validated org claim, and a caller therefore has no way to name another tenant\'s namespace. `path` narrows to a subpath and `env` selects the environment; both are also accepted under the operator\'s spellings, `secretPath` and `environment`. An omitted `env` means every environment and an omitted `path` means the whole org, because a default here reported a populated store as empty.  Admission is fail-closed and in order: a validated member, an org that is a DNS-1123 label, and a store holding a master key — 403, 400 and 503 respectively, all decided before any record is touched.
         * @summary Lists the secrets your org holds, without their values.
         * @param {string} [env] Env selects the environment, which is part of a secret\&#39;s storage key. OMITTED means EVERY environment — this is the enumeration surface, so it must be able to answer \&quot;what is in here\&quot; without being told where to look.
         * @param {string} [environment] Environment is the KMS operator\&#39;s spelling of Env, accepted so one caller need not learn the other\&#39;s vocabulary. Env wins when both are sent.
         * @param {string} [path] Path narrows the listing to one subtree beneath the caller\&#39;s org root, as a &#x60;/&#x60;-separated path such as &#x60;/ci&#x60;. OMITTED means the whole org.
         * @param {string} [secretPath] SecretPath is the KMS operator\&#39;s spelling of Path. Path wins when both are sent.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKmsSecrets: async (env?: string, environment?: string, path?: string, secretPath?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/kms/secrets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (env !== undefined) {
                localVarQueryParameter['env'] = env;
            }

            if (environment !== undefined) {
                localVarQueryParameter['environment'] = environment;
            }

            if (path !== undefined) {
                localVarQueryParameter['path'] = path;
            }

            if (secretPath !== undefined) {
                localVarQueryParameter['secretPath'] = secretPath;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Exchanges a machine credential for an IAM bearer token.  Takes a tenant\'s machine credential — a client id and client secret — and returns an owner-scoped IAM access token with its lifetime, which is the bearer the caller then carries on the org-scoped secret operations.  It is deliberately public and unauthenticated, because it IS the credential exchange and runs before any principal exists. That makes it the one route in this subsystem rate-limited PER SOURCE IP, keyed on the real TCP peer rather than on any caller-supplied header, and body-capped in the same place.  The submitted secret is never logged and never echoed, and failures collapse to one clean status with no upstream detail: 401 when the credential does not authenticate, 502 when the identity provider is unreachable, 503 when no issuer is configured. That is on purpose — a richer error would be a validity oracle for guessed credentials.
         * @summary Exchanges a machine credential for an IAM bearer token.
         * @param {KmsLogin} kmsLogin 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postKmsAuthLogin: async (kmsLogin: KmsLogin, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'kmsLogin' is not null or undefined
            assertParamExists('postKmsAuthLogin', 'kmsLogin', kmsLogin)
            const localVarPath = `/v1/kms/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(kmsLogin, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Stores or replaces one secret in your org.  Upserts one secret under the caller\'s own org. The value is sealed before it is written — a fresh per-secret data key, itself wrapped by the master key — so plaintext never reaches disk. The receipt confirms the name and environment that were written and does not echo the value.  `env` is REQUIRED on a write and has no default, which is the rule most easily got wrong here: reads and deletes still fall back to the default environment for older callers, but a write must not, because the environment is part of the storage key. A silently defaulted write lands in a bucket the readers that resolve project, environment and path never look in, and the stale value keeps being served — so the write fails loudly instead.  `name` is required, `path` is an optional subpath beneath the org root, and the org is taken from the validated claim rather than the body.  Requires ADMIN authority over the org — a member reads, an admin writes. A machine credential holds no membership and so is never an org admin: it can read the secrets it was issued for and cannot replace one. Fail-closed admission, in order: admin of the org, well-formed org, master key present — 403, 400 and 503, all decided before any record is touched.
         * @summary Stores or replaces one secret in your org.
         * @param {KmsPut} kmsPut 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postKmsSecrets: async (kmsPut: KmsPut, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'kmsPut' is not null or undefined
            assertParamExists('postKmsSecrets', 'kmsPut', kmsPut)
            const localVarPath = `/v1/kms/secrets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(kmsPut, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * KmsApi - functional programming interface
 * @export
 */
export const KmsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = KmsApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns the runtime configuration for the KMS console.  What the console needs before anyone has signed in: the brand, the OIDC issuer it authenticates against, the API base for this subsystem and the path of the login exchange.  Public on purpose, and it holds nothing sensitive — it is deliberately kept under this subsystem\'s own namespace rather than under an admin prefix, so a gateway that admin-gates the admin routes cannot break the console\'s legitimate pre-login fetch.
         * @summary Returns the runtime configuration for the KMS console.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKmsConfig(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KmsConfig>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKmsConfig(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KmsApi.getKmsConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Reports whether this broker can actually serve secrets.  A real readiness probe, not a liveness stub: 200 only when the store is open AND a master key is configured, with `signing` reporting whether signing keys are set up too. Anything less answers 503 with `ready:false` and the reason — no in-process store, or no master key — which are exactly the two states in which the secret operations refuse.  Not token-gated, because the platform must be able to probe it without a credential. It reports the broker\'s configuration state only; no secret, no key material and no tenant name appears in it.
         * @summary Reports whether this broker can actually serve secrets.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKmsHealth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KmsHealth>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKmsHealth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KmsApi.getKmsHealth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lists the secrets your org holds, without their values.  Returns the METADATA of the caller\'s own secrets: each one\'s name, path, environment and sealing scheme. No value and no ciphertext is included — this operation exists to enumerate what is held, and reading a value is a separate, per-secret call.  Scoped to the caller\'s own org and nothing else, structurally: there is no org in the path, the store root is derived from the validated org claim, and a caller therefore has no way to name another tenant\'s namespace. `path` narrows to a subpath and `env` selects the environment; both are also accepted under the operator\'s spellings, `secretPath` and `environment`. An omitted `env` means every environment and an omitted `path` means the whole org, because a default here reported a populated store as empty.  Admission is fail-closed and in order: a validated member, an org that is a DNS-1123 label, and a store holding a master key — 403, 400 and 503 respectively, all decided before any record is touched.
         * @summary Lists the secrets your org holds, without their values.
         * @param {string} [env] Env selects the environment, which is part of a secret\&#39;s storage key. OMITTED means EVERY environment — this is the enumeration surface, so it must be able to answer \&quot;what is in here\&quot; without being told where to look.
         * @param {string} [environment] Environment is the KMS operator\&#39;s spelling of Env, accepted so one caller need not learn the other\&#39;s vocabulary. Env wins when both are sent.
         * @param {string} [path] Path narrows the listing to one subtree beneath the caller\&#39;s org root, as a &#x60;/&#x60;-separated path such as &#x60;/ci&#x60;. OMITTED means the whole org.
         * @param {string} [secretPath] SecretPath is the KMS operator\&#39;s spelling of Path. Path wins when both are sent.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKmsSecrets(env?: string, environment?: string, path?: string, secretPath?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KmsSecrets>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKmsSecrets(env, environment, path, secretPath, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KmsApi.getKmsSecrets']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Exchanges a machine credential for an IAM bearer token.  Takes a tenant\'s machine credential — a client id and client secret — and returns an owner-scoped IAM access token with its lifetime, which is the bearer the caller then carries on the org-scoped secret operations.  It is deliberately public and unauthenticated, because it IS the credential exchange and runs before any principal exists. That makes it the one route in this subsystem rate-limited PER SOURCE IP, keyed on the real TCP peer rather than on any caller-supplied header, and body-capped in the same place.  The submitted secret is never logged and never echoed, and failures collapse to one clean status with no upstream detail: 401 when the credential does not authenticate, 502 when the identity provider is unreachable, 503 when no issuer is configured. That is on purpose — a richer error would be a validity oracle for guessed credentials.
         * @summary Exchanges a machine credential for an IAM bearer token.
         * @param {KmsLogin} kmsLogin 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postKmsAuthLogin(kmsLogin: KmsLogin, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KmsToken>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postKmsAuthLogin(kmsLogin, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KmsApi.postKmsAuthLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Stores or replaces one secret in your org.  Upserts one secret under the caller\'s own org. The value is sealed before it is written — a fresh per-secret data key, itself wrapped by the master key — so plaintext never reaches disk. The receipt confirms the name and environment that were written and does not echo the value.  `env` is REQUIRED on a write and has no default, which is the rule most easily got wrong here: reads and deletes still fall back to the default environment for older callers, but a write must not, because the environment is part of the storage key. A silently defaulted write lands in a bucket the readers that resolve project, environment and path never look in, and the stale value keeps being served — so the write fails loudly instead.  `name` is required, `path` is an optional subpath beneath the org root, and the org is taken from the validated claim rather than the body.  Requires ADMIN authority over the org — a member reads, an admin writes. A machine credential holds no membership and so is never an org admin: it can read the secrets it was issued for and cannot replace one. Fail-closed admission, in order: admin of the org, well-formed org, master key present — 403, 400 and 503, all decided before any record is touched.
         * @summary Stores or replaces one secret in your org.
         * @param {KmsPut} kmsPut 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postKmsSecrets(kmsPut: KmsPut, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KmsStored>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postKmsSecrets(kmsPut, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KmsApi.postKmsSecrets']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * KmsApi - factory interface
 * @export
 */
export const KmsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = KmsApiFp(configuration)
    return {
        /**
         * Returns the runtime configuration for the KMS console.  What the console needs before anyone has signed in: the brand, the OIDC issuer it authenticates against, the API base for this subsystem and the path of the login exchange.  Public on purpose, and it holds nothing sensitive — it is deliberately kept under this subsystem\'s own namespace rather than under an admin prefix, so a gateway that admin-gates the admin routes cannot break the console\'s legitimate pre-login fetch.
         * @summary Returns the runtime configuration for the KMS console.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKmsConfig(options?: RawAxiosRequestConfig): AxiosPromise<KmsConfig> {
            return localVarFp.getKmsConfig(options).then((request) => request(axios, basePath));
        },
        /**
         * Reports whether this broker can actually serve secrets.  A real readiness probe, not a liveness stub: 200 only when the store is open AND a master key is configured, with `signing` reporting whether signing keys are set up too. Anything less answers 503 with `ready:false` and the reason — no in-process store, or no master key — which are exactly the two states in which the secret operations refuse.  Not token-gated, because the platform must be able to probe it without a credential. It reports the broker\'s configuration state only; no secret, no key material and no tenant name appears in it.
         * @summary Reports whether this broker can actually serve secrets.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKmsHealth(options?: RawAxiosRequestConfig): AxiosPromise<KmsHealth> {
            return localVarFp.getKmsHealth(options).then((request) => request(axios, basePath));
        },
        /**
         * Lists the secrets your org holds, without their values.  Returns the METADATA of the caller\'s own secrets: each one\'s name, path, environment and sealing scheme. No value and no ciphertext is included — this operation exists to enumerate what is held, and reading a value is a separate, per-secret call.  Scoped to the caller\'s own org and nothing else, structurally: there is no org in the path, the store root is derived from the validated org claim, and a caller therefore has no way to name another tenant\'s namespace. `path` narrows to a subpath and `env` selects the environment; both are also accepted under the operator\'s spellings, `secretPath` and `environment`. An omitted `env` means every environment and an omitted `path` means the whole org, because a default here reported a populated store as empty.  Admission is fail-closed and in order: a validated member, an org that is a DNS-1123 label, and a store holding a master key — 403, 400 and 503 respectively, all decided before any record is touched.
         * @summary Lists the secrets your org holds, without their values.
         * @param {KmsApiGetKmsSecretsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKmsSecrets(requestParameters: KmsApiGetKmsSecretsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<KmsSecrets> {
            return localVarFp.getKmsSecrets(requestParameters.env, requestParameters.environment, requestParameters.path, requestParameters.secretPath, options).then((request) => request(axios, basePath));
        },
        /**
         * Exchanges a machine credential for an IAM bearer token.  Takes a tenant\'s machine credential — a client id and client secret — and returns an owner-scoped IAM access token with its lifetime, which is the bearer the caller then carries on the org-scoped secret operations.  It is deliberately public and unauthenticated, because it IS the credential exchange and runs before any principal exists. That makes it the one route in this subsystem rate-limited PER SOURCE IP, keyed on the real TCP peer rather than on any caller-supplied header, and body-capped in the same place.  The submitted secret is never logged and never echoed, and failures collapse to one clean status with no upstream detail: 401 when the credential does not authenticate, 502 when the identity provider is unreachable, 503 when no issuer is configured. That is on purpose — a richer error would be a validity oracle for guessed credentials.
         * @summary Exchanges a machine credential for an IAM bearer token.
         * @param {KmsApiPostKmsAuthLoginRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postKmsAuthLogin(requestParameters: KmsApiPostKmsAuthLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<KmsToken> {
            return localVarFp.postKmsAuthLogin(requestParameters.kmsLogin, options).then((request) => request(axios, basePath));
        },
        /**
         * Stores or replaces one secret in your org.  Upserts one secret under the caller\'s own org. The value is sealed before it is written — a fresh per-secret data key, itself wrapped by the master key — so plaintext never reaches disk. The receipt confirms the name and environment that were written and does not echo the value.  `env` is REQUIRED on a write and has no default, which is the rule most easily got wrong here: reads and deletes still fall back to the default environment for older callers, but a write must not, because the environment is part of the storage key. A silently defaulted write lands in a bucket the readers that resolve project, environment and path never look in, and the stale value keeps being served — so the write fails loudly instead.  `name` is required, `path` is an optional subpath beneath the org root, and the org is taken from the validated claim rather than the body.  Requires ADMIN authority over the org — a member reads, an admin writes. A machine credential holds no membership and so is never an org admin: it can read the secrets it was issued for and cannot replace one. Fail-closed admission, in order: admin of the org, well-formed org, master key present — 403, 400 and 503, all decided before any record is touched.
         * @summary Stores or replaces one secret in your org.
         * @param {KmsApiPostKmsSecretsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postKmsSecrets(requestParameters: KmsApiPostKmsSecretsRequest, options?: RawAxiosRequestConfig): AxiosPromise<KmsStored> {
            return localVarFp.postKmsSecrets(requestParameters.kmsPut, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getKmsSecrets operation in KmsApi.
 * @export
 * @interface KmsApiGetKmsSecretsRequest
 */
export interface KmsApiGetKmsSecretsRequest {
    /**
     * Env selects the environment, which is part of a secret\&#39;s storage key. OMITTED means EVERY environment — this is the enumeration surface, so it must be able to answer \&quot;what is in here\&quot; without being told where to look.
     * @type {string}
     * @memberof KmsApiGetKmsSecrets
     */
    readonly env?: string

    /**
     * Environment is the KMS operator\&#39;s spelling of Env, accepted so one caller need not learn the other\&#39;s vocabulary. Env wins when both are sent.
     * @type {string}
     * @memberof KmsApiGetKmsSecrets
     */
    readonly environment?: string

    /**
     * Path narrows the listing to one subtree beneath the caller\&#39;s org root, as a &#x60;/&#x60;-separated path such as &#x60;/ci&#x60;. OMITTED means the whole org.
     * @type {string}
     * @memberof KmsApiGetKmsSecrets
     */
    readonly path?: string

    /**
     * SecretPath is the KMS operator\&#39;s spelling of Path. Path wins when both are sent.
     * @type {string}
     * @memberof KmsApiGetKmsSecrets
     */
    readonly secretPath?: string
}

/**
 * Request parameters for postKmsAuthLogin operation in KmsApi.
 * @export
 * @interface KmsApiPostKmsAuthLoginRequest
 */
export interface KmsApiPostKmsAuthLoginRequest {
    /**
     * 
     * @type {KmsLogin}
     * @memberof KmsApiPostKmsAuthLogin
     */
    readonly kmsLogin: KmsLogin
}

/**
 * Request parameters for postKmsSecrets operation in KmsApi.
 * @export
 * @interface KmsApiPostKmsSecretsRequest
 */
export interface KmsApiPostKmsSecretsRequest {
    /**
     * 
     * @type {KmsPut}
     * @memberof KmsApiPostKmsSecrets
     */
    readonly kmsPut: KmsPut
}

/**
 * KmsApi - object-oriented interface
 * @export
 * @class KmsApi
 * @extends {BaseAPI}
 */
export class KmsApi extends BaseAPI {
    /**
     * Returns the runtime configuration for the KMS console.  What the console needs before anyone has signed in: the brand, the OIDC issuer it authenticates against, the API base for this subsystem and the path of the login exchange.  Public on purpose, and it holds nothing sensitive — it is deliberately kept under this subsystem\'s own namespace rather than under an admin prefix, so a gateway that admin-gates the admin routes cannot break the console\'s legitimate pre-login fetch.
     * @summary Returns the runtime configuration for the KMS console.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KmsApi
     */
    public getKmsConfig(options?: RawAxiosRequestConfig) {
        return KmsApiFp(this.configuration).getKmsConfig(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Reports whether this broker can actually serve secrets.  A real readiness probe, not a liveness stub: 200 only when the store is open AND a master key is configured, with `signing` reporting whether signing keys are set up too. Anything less answers 503 with `ready:false` and the reason — no in-process store, or no master key — which are exactly the two states in which the secret operations refuse.  Not token-gated, because the platform must be able to probe it without a credential. It reports the broker\'s configuration state only; no secret, no key material and no tenant name appears in it.
     * @summary Reports whether this broker can actually serve secrets.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KmsApi
     */
    public getKmsHealth(options?: RawAxiosRequestConfig) {
        return KmsApiFp(this.configuration).getKmsHealth(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lists the secrets your org holds, without their values.  Returns the METADATA of the caller\'s own secrets: each one\'s name, path, environment and sealing scheme. No value and no ciphertext is included — this operation exists to enumerate what is held, and reading a value is a separate, per-secret call.  Scoped to the caller\'s own org and nothing else, structurally: there is no org in the path, the store root is derived from the validated org claim, and a caller therefore has no way to name another tenant\'s namespace. `path` narrows to a subpath and `env` selects the environment; both are also accepted under the operator\'s spellings, `secretPath` and `environment`. An omitted `env` means every environment and an omitted `path` means the whole org, because a default here reported a populated store as empty.  Admission is fail-closed and in order: a validated member, an org that is a DNS-1123 label, and a store holding a master key — 403, 400 and 503 respectively, all decided before any record is touched.
     * @summary Lists the secrets your org holds, without their values.
     * @param {KmsApiGetKmsSecretsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KmsApi
     */
    public getKmsSecrets(requestParameters: KmsApiGetKmsSecretsRequest = {}, options?: RawAxiosRequestConfig) {
        return KmsApiFp(this.configuration).getKmsSecrets(requestParameters.env, requestParameters.environment, requestParameters.path, requestParameters.secretPath, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Exchanges a machine credential for an IAM bearer token.  Takes a tenant\'s machine credential — a client id and client secret — and returns an owner-scoped IAM access token with its lifetime, which is the bearer the caller then carries on the org-scoped secret operations.  It is deliberately public and unauthenticated, because it IS the credential exchange and runs before any principal exists. That makes it the one route in this subsystem rate-limited PER SOURCE IP, keyed on the real TCP peer rather than on any caller-supplied header, and body-capped in the same place.  The submitted secret is never logged and never echoed, and failures collapse to one clean status with no upstream detail: 401 when the credential does not authenticate, 502 when the identity provider is unreachable, 503 when no issuer is configured. That is on purpose — a richer error would be a validity oracle for guessed credentials.
     * @summary Exchanges a machine credential for an IAM bearer token.
     * @param {KmsApiPostKmsAuthLoginRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KmsApi
     */
    public postKmsAuthLogin(requestParameters: KmsApiPostKmsAuthLoginRequest, options?: RawAxiosRequestConfig) {
        return KmsApiFp(this.configuration).postKmsAuthLogin(requestParameters.kmsLogin, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Stores or replaces one secret in your org.  Upserts one secret under the caller\'s own org. The value is sealed before it is written — a fresh per-secret data key, itself wrapped by the master key — so plaintext never reaches disk. The receipt confirms the name and environment that were written and does not echo the value.  `env` is REQUIRED on a write and has no default, which is the rule most easily got wrong here: reads and deletes still fall back to the default environment for older callers, but a write must not, because the environment is part of the storage key. A silently defaulted write lands in a bucket the readers that resolve project, environment and path never look in, and the stale value keeps being served — so the write fails loudly instead.  `name` is required, `path` is an optional subpath beneath the org root, and the org is taken from the validated claim rather than the body.  Requires ADMIN authority over the org — a member reads, an admin writes. A machine credential holds no membership and so is never an org admin: it can read the secrets it was issued for and cannot replace one. Fail-closed admission, in order: admin of the org, well-formed org, master key present — 403, 400 and 503, all decided before any record is touched.
     * @summary Stores or replaces one secret in your org.
     * @param {KmsApiPostKmsSecretsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KmsApi
     */
    public postKmsSecrets(requestParameters: KmsApiPostKmsSecretsRequest, options?: RawAxiosRequestConfig) {
        return KmsApiFp(this.configuration).postKmsSecrets(requestParameters.kmsPut, options).then((request) => request(this.axios, this.basePath));
    }
}

