/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PlatformTRPCResult } from '../models';
/**
 * PlatformBillingApi - axios parameter creator
 * @export
 */
export const PlatformBillingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get account balance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        platformBillingGetBalance: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/platform/billing/getBalance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List subscription plans
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        platformBillingGetPlans: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/platform/billing/getPlans`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PlatformBillingApi - functional programming interface
 * @export
 */
export const PlatformBillingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PlatformBillingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get account balance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async platformBillingGetBalance(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlatformTRPCResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.platformBillingGetBalance(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlatformBillingApi.platformBillingGetBalance']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List subscription plans
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async platformBillingGetPlans(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlatformTRPCResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.platformBillingGetPlans(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlatformBillingApi.platformBillingGetPlans']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PlatformBillingApi - factory interface
 * @export
 */
export const PlatformBillingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PlatformBillingApiFp(configuration)
    return {
        /**
         * 
         * @summary Get account balance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        platformBillingGetBalance(options?: RawAxiosRequestConfig): AxiosPromise<PlatformTRPCResult> {
            return localVarFp.platformBillingGetBalance(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List subscription plans
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        platformBillingGetPlans(options?: RawAxiosRequestConfig): AxiosPromise<PlatformTRPCResult> {
            return localVarFp.platformBillingGetPlans(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PlatformBillingApi - object-oriented interface
 * @export
 * @class PlatformBillingApi
 * @extends {BaseAPI}
 */
export class PlatformBillingApi extends BaseAPI {
    /**
     * 
     * @summary Get account balance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlatformBillingApi
     */
    public platformBillingGetBalance(options?: RawAxiosRequestConfig) {
        return PlatformBillingApiFp(this.configuration).platformBillingGetBalance(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List subscription plans
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlatformBillingApi
     */
    public platformBillingGetPlans(options?: RawAxiosRequestConfig) {
        return PlatformBillingApiFp(this.configuration).platformBillingGetPlans(options).then((request) => request(this.axios, this.basePath));
    }
}

