/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Blob } from '../models';
// @ts-ignore
import type { EndIn } from '../models';
// @ts-ignore
import type { LeaseIn } from '../models';
// @ts-ignore
import type { Leased } from '../models';
// @ts-ignore
import type { PathIn } from '../models';
// @ts-ignore
import type { Ran } from '../models';
// @ts-ignore
import type { RunIn } from '../models';
// @ts-ignore
import type { StopIn } from '../models';
// @ts-ignore
import type { Stopped } from '../models';
// @ts-ignore
import type { WriteIn } from '../models';
// @ts-ignore
import type { Wrote } from '../models';
/**
 * SandboxesApi - axios parameter creator
 * @export
 */
export const SandboxesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Stops the sandbox\'s pod and drops the lease. The VOLUME survives by default, so a `dev` or `desktop` sandbox can be leased again over the same project and find its checkout where it left it.  `purge=1` deletes the volume too. It is opt-in because it is the one part of this that cannot be undone.
         * @summary End a sandbox
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteV1SandboxesById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteV1SandboxesById', 'id', id)
            const localVarPath = `/v1/sandboxes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Ends the caller\'s sandbox lease: the pod goes, and the volume goes only when the caller asked for that too.
         * @summary End a sandbox and release it
         * @param {EndIn} endIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        endSandbox: async (endIn: EndIn, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'endIn' is not null or undefined
            assertParamExists('endSandbox', 'endIn', endIn)
            const localVarPath = `/v1/sandboxes/end`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(endIn, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lists the caller org\'s sandboxes, newest first. `project` and `status` narrow it, and both are read from the QUERY STRING.  It answers from the org\'s own store rather than from the cluster, so a sandbox whose pod has since died still appears, carrying the status it was last known to have. That is deliberate: a lease you are being charged for should not vanish from the list because the thing behind it fell over.
         * @summary The sandboxes this org holds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1Sandboxes: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/sandboxes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns one of the caller org\'s sandboxes. An id belonging to another org answers 404 and not 403 — a 403 would confirm the id exists, and whether a given sandbox exists is itself a cross-tenant fact.
         * @summary One sandbox
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1SandboxesById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getV1SandboxesById', 'id', id)
            const localVarPath = `/v1/sandboxes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Reads one file from the sandbox\'s project directory as text, or lists the entries when the path names a directory. Paths resolve under the project root and a path that climbs out is refused rather than rewritten.
         * @summary Read a file, or list a directory
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1SandboxesByIdFs: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getV1SandboxesByIdFs', 'id', id)
            const localVarPath = `/v1/sandboxes/{id}/fs`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * A complete, self-contained terminal — xterm inline, no other origin — that opens its own socket and runs a shell in this sandbox. Embed it in an iframe and there is nothing else to build.  `ticket` is the credential from the POST above and `arg` names the session (see the socket below); both are simply carried through to the socket. The page is NOT gated — it is inert markup and does not redeem the ticket, because a ticket is spent once and a page that spent it would hold a credential that no longer opens anything.  When the terminal is up it posts `{source:\"hanzo-term\", ready:true}` to its parent frame, so a host can tell a live terminal from a page that failed into something else. `frame-ancestors` admits our own brands\' hosts and nothing further.
         * @summary The terminal, as a page
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1SandboxesByIdTerminal: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getV1SandboxesByIdTerminal', 'id', id)
            const localVarPath = `/v1/sandboxes/{id}/terminal`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Upgrades to a WebSocket carrying a login shell on a pseudo-terminal inside the sandbox — for a host that brings its own emulator. Requires `ticket`; a missing, expired or already-spent one answers 401 without upgrading.  THE WIRE. A text frame is stdin, unless it is the one control object `{\"resize\":{\"cols\":N,\"rows\":M}}`; a binary frame is always stdin. Output comes back as BINARY frames, because a pty emits arbitrary bytes cut at arbitrary offsets and a text frame carrying half a rune is one the browser closes the connection over.  `arg` names a SESSION: the shell runs under `tmux new -A -s <arg>`, which attaches to that session if it exists and creates it if it does not — so one sandbox holds as many terminals as a caller has names for. It is 1-64 characters of letters, digits, `-` or `_` and may not begin with `-`; anything else is 400. Without `arg` the shell is unnamed and unmultiplexed.  The shell is `zsh -l`, falling back to `bash -l` and then to `sh -l`, and to the plain shell again when the image has no tmux. Every step is a preference and none is a requirement: whatever else the image carries — the hanzo CLI included — is a command to type, never a condition for getting a prompt.
         * @summary The terminal, as a socket
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1SandboxesByIdTerminalWs: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getV1SandboxesByIdTerminalWs', 'id', id)
            const localVarPath = `/v1/sandboxes/{id}/terminal/ws`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Leases the caller\'s sandbox, or returns the one it named if that lease is still running.  What comes back is a real computer: a pod under a runtime boundary with a toolchain already in it, its own filesystem, and a lease that ends it. Every other op here acts on the one this returns.
         * @summary Lease a sandbox — a real computer — or resume one you hold
         * @param {LeaseIn} leaseIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        leaseSandbox: async (leaseIn: LeaseIn, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'leaseIn' is not null or undefined
            assertParamExists('leaseSandbox', 'leaseIn', leaseIn)
            const localVarPath = `/v1/sandboxes/lease`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(leaseIn, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a sandbox and returns it. `class` is one of `exec`, `dev` or `desktop`; `dev` and `desktop` are attached to a `project`, which is required for them and names the volume the work persists on. `ttlSec` bounds the lease, and `image` overrides the class default.  This is the ONLY path that creates cluster objects. The isolation boundary is the pod\'s runtime class, one field, so what a sandbox is confined by is a deployment decision rather than anything this operation negotiates.
         * @summary Lease a sandbox
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1Sandboxes: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/sandboxes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Runs a command inside the sandbox and returns its exit code, stdout and stderr. A non-zero exit is a SUCCESSFUL call carrying a failed program — the HTTP status stays 200, because \"the tests failed\" and \"the sandbox is broken\" are different facts.  NOTHING RUNS IN cloud. The command is streamed to the Kubernetes exec subresource of the sandbox\'s pod, which runs under the gVisor runtime class. The sandbox is addressed by pod NAME through the apiserver, never by address.
         * @summary Run a command in a sandbox
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1SandboxesByIdExec: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('postV1SandboxesByIdExec', 'id', id)
            const localVarPath = `/v1/sandboxes/{id}/exec`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Writes the request body to one file in the sandbox\'s project directory, creating parent directories. Same confinement as the read above.
         * @summary Write a file
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1SandboxesByIdFs: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('postV1SandboxesByIdFs', 'id', id)
            const localVarPath = `/v1/sandboxes/{id}/fs`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Mints a SINGLE-USE ticket for one interactive terminal in this sandbox and returns `{ticket, expiresIn, url}`, where url is the terminal PAGE with the ticket already on it.  It exists because a browser carries no Authorization header into a WebSocket or an iframe, so a terminal cannot be authenticated the way every other route here is. The ticket is a credential MINTED for that one terminal: bound to this org and this sandbox, valid for thirty seconds, and gone the first time it is presented. A long-lived bearer in a query string would instead be written into every access log on the path.  Mint one per terminal, and mint a fresh one to reconnect.
         * @summary Open a terminal
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1SandboxesByIdTerminalTicket: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('postV1SandboxesByIdTerminalTicket', 'id', id)
            const localVarPath = `/v1/sandboxes/{id}/terminal/ticket`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Reads one path in the caller\'s sandbox: a file\'s bytes, or a directory\'s entries when the path names one.
         * @summary Read a file from a sandbox you hold
         * @param {PathIn} pathIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readSandboxFile: async (pathIn: PathIn, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pathIn' is not null or undefined
            assertParamExists('readSandboxFile', 'pathIn', pathIn)
            const localVarPath = `/v1/sandboxes/read`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pathIn, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Runs one command inside the caller\'s sandbox and answers its exit code, stdout and stderr. A non-zero exit is a successful call carrying a failed program, so it comes back as data and not as an error.  Name a `session` and the command NARRATES INTO IT: its output is appended to that session\'s live log as the program produces it, so anything watching the session — GET /v1/agents/sessions/stream, scoped to one run with ?root= — watches the work happen rather than waiting for the verdict. Without it the call is what it always was: silent until it returns, which for an agentic run is twenty-five minutes of blank screen.  The session is named; the TENANT is not. It is the org the caller already proved, so a session belonging to somebody else is absent from the org this call acts for and the append is refused there.
         * @summary Run a command in a sandbox you hold and read its output
         * @param {RunIn} runIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runInSandbox: async (runIn: RunIn, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'runIn' is not null or undefined
            assertParamExists('runInSandbox', 'runIn', runIn)
            const localVarPath = `/v1/sandboxes/run`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(runIn, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Interrupts whatever the caller\'s sandbox is running and answers how many commands it ended. The sandbox stays leased — stop ends the WORK, end ends the RESOURCE — so whoever stopped a run can still read what it left behind.
         * @summary Stop what a sandbox is running, and keep the sandbox
         * @param {StopIn} stopIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stopRun: async (stopIn: StopIn, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stopIn' is not null or undefined
            assertParamExists('stopRun', 'stopIn', stopIn)
            const localVarPath = `/v1/sandboxes/stop`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(stopIn, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Writes bytes to one path in the caller\'s sandbox, creating parents, and answers the resolved path.
         * @summary Write a file into a sandbox you hold
         * @param {WriteIn} writeIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        writeSandboxFile: async (writeIn: WriteIn, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'writeIn' is not null or undefined
            assertParamExists('writeSandboxFile', 'writeIn', writeIn)
            const localVarPath = `/v1/sandboxes/write`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(writeIn, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SandboxesApi - functional programming interface
 * @export
 */
export const SandboxesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SandboxesApiAxiosParamCreator(configuration)
    return {
        /**
         * Stops the sandbox\'s pod and drops the lease. The VOLUME survives by default, so a `dev` or `desktop` sandbox can be leased again over the same project and find its checkout where it left it.  `purge=1` deletes the volume too. It is opt-in because it is the one part of this that cannot be undone.
         * @summary End a sandbox
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteV1SandboxesById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteV1SandboxesById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.deleteV1SandboxesById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Ends the caller\'s sandbox lease: the pod goes, and the volume goes only when the caller asked for that too.
         * @summary End a sandbox and release it
         * @param {EndIn} endIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async endSandbox(endIn: EndIn, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.endSandbox(endIn, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.endSandbox']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lists the caller org\'s sandboxes, newest first. `project` and `status` narrow it, and both are read from the QUERY STRING.  It answers from the org\'s own store rather than from the cluster, so a sandbox whose pod has since died still appears, carrying the status it was last known to have. That is deliberate: a lease you are being charged for should not vanish from the list because the thing behind it fell over.
         * @summary The sandboxes this org holds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1Sandboxes(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getV1Sandboxes(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.getV1Sandboxes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns one of the caller org\'s sandboxes. An id belonging to another org answers 404 and not 403 — a 403 would confirm the id exists, and whether a given sandbox exists is itself a cross-tenant fact.
         * @summary One sandbox
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1SandboxesById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getV1SandboxesById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.getV1SandboxesById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Reads one file from the sandbox\'s project directory as text, or lists the entries when the path names a directory. Paths resolve under the project root and a path that climbs out is refused rather than rewritten.
         * @summary Read a file, or list a directory
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1SandboxesByIdFs(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getV1SandboxesByIdFs(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.getV1SandboxesByIdFs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * A complete, self-contained terminal — xterm inline, no other origin — that opens its own socket and runs a shell in this sandbox. Embed it in an iframe and there is nothing else to build.  `ticket` is the credential from the POST above and `arg` names the session (see the socket below); both are simply carried through to the socket. The page is NOT gated — it is inert markup and does not redeem the ticket, because a ticket is spent once and a page that spent it would hold a credential that no longer opens anything.  When the terminal is up it posts `{source:\"hanzo-term\", ready:true}` to its parent frame, so a host can tell a live terminal from a page that failed into something else. `frame-ancestors` admits our own brands\' hosts and nothing further.
         * @summary The terminal, as a page
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1SandboxesByIdTerminal(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getV1SandboxesByIdTerminal(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.getV1SandboxesByIdTerminal']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Upgrades to a WebSocket carrying a login shell on a pseudo-terminal inside the sandbox — for a host that brings its own emulator. Requires `ticket`; a missing, expired or already-spent one answers 401 without upgrading.  THE WIRE. A text frame is stdin, unless it is the one control object `{\"resize\":{\"cols\":N,\"rows\":M}}`; a binary frame is always stdin. Output comes back as BINARY frames, because a pty emits arbitrary bytes cut at arbitrary offsets and a text frame carrying half a rune is one the browser closes the connection over.  `arg` names a SESSION: the shell runs under `tmux new -A -s <arg>`, which attaches to that session if it exists and creates it if it does not — so one sandbox holds as many terminals as a caller has names for. It is 1-64 characters of letters, digits, `-` or `_` and may not begin with `-`; anything else is 400. Without `arg` the shell is unnamed and unmultiplexed.  The shell is `zsh -l`, falling back to `bash -l` and then to `sh -l`, and to the plain shell again when the image has no tmux. Every step is a preference and none is a requirement: whatever else the image carries — the hanzo CLI included — is a command to type, never a condition for getting a prompt.
         * @summary The terminal, as a socket
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1SandboxesByIdTerminalWs(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getV1SandboxesByIdTerminalWs(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.getV1SandboxesByIdTerminalWs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Leases the caller\'s sandbox, or returns the one it named if that lease is still running.  What comes back is a real computer: a pod under a runtime boundary with a toolchain already in it, its own filesystem, and a lease that ends it. Every other op here acts on the one this returns.
         * @summary Lease a sandbox — a real computer — or resume one you hold
         * @param {LeaseIn} leaseIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async leaseSandbox(leaseIn: LeaseIn, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Leased>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.leaseSandbox(leaseIn, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.leaseSandbox']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a sandbox and returns it. `class` is one of `exec`, `dev` or `desktop`; `dev` and `desktop` are attached to a `project`, which is required for them and names the volume the work persists on. `ttlSec` bounds the lease, and `image` overrides the class default.  This is the ONLY path that creates cluster objects. The isolation boundary is the pod\'s runtime class, one field, so what a sandbox is confined by is a deployment decision rather than anything this operation negotiates.
         * @summary Lease a sandbox
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postV1Sandboxes(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postV1Sandboxes(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.postV1Sandboxes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Runs a command inside the sandbox and returns its exit code, stdout and stderr. A non-zero exit is a SUCCESSFUL call carrying a failed program — the HTTP status stays 200, because \"the tests failed\" and \"the sandbox is broken\" are different facts.  NOTHING RUNS IN cloud. The command is streamed to the Kubernetes exec subresource of the sandbox\'s pod, which runs under the gVisor runtime class. The sandbox is addressed by pod NAME through the apiserver, never by address.
         * @summary Run a command in a sandbox
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postV1SandboxesByIdExec(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postV1SandboxesByIdExec(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.postV1SandboxesByIdExec']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Writes the request body to one file in the sandbox\'s project directory, creating parent directories. Same confinement as the read above.
         * @summary Write a file
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postV1SandboxesByIdFs(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postV1SandboxesByIdFs(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.postV1SandboxesByIdFs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Mints a SINGLE-USE ticket for one interactive terminal in this sandbox and returns `{ticket, expiresIn, url}`, where url is the terminal PAGE with the ticket already on it.  It exists because a browser carries no Authorization header into a WebSocket or an iframe, so a terminal cannot be authenticated the way every other route here is. The ticket is a credential MINTED for that one terminal: bound to this org and this sandbox, valid for thirty seconds, and gone the first time it is presented. A long-lived bearer in a query string would instead be written into every access log on the path.  Mint one per terminal, and mint a fresh one to reconnect.
         * @summary Open a terminal
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postV1SandboxesByIdTerminalTicket(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postV1SandboxesByIdTerminalTicket(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.postV1SandboxesByIdTerminalTicket']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Reads one path in the caller\'s sandbox: a file\'s bytes, or a directory\'s entries when the path names one.
         * @summary Read a file from a sandbox you hold
         * @param {PathIn} pathIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readSandboxFile(pathIn: PathIn, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Blob>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readSandboxFile(pathIn, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.readSandboxFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Runs one command inside the caller\'s sandbox and answers its exit code, stdout and stderr. A non-zero exit is a successful call carrying a failed program, so it comes back as data and not as an error.  Name a `session` and the command NARRATES INTO IT: its output is appended to that session\'s live log as the program produces it, so anything watching the session — GET /v1/agents/sessions/stream, scoped to one run with ?root= — watches the work happen rather than waiting for the verdict. Without it the call is what it always was: silent until it returns, which for an agentic run is twenty-five minutes of blank screen.  The session is named; the TENANT is not. It is the org the caller already proved, so a session belonging to somebody else is absent from the org this call acts for and the append is refused there.
         * @summary Run a command in a sandbox you hold and read its output
         * @param {RunIn} runIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runInSandbox(runIn: RunIn, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Ran>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runInSandbox(runIn, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.runInSandbox']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Interrupts whatever the caller\'s sandbox is running and answers how many commands it ended. The sandbox stays leased — stop ends the WORK, end ends the RESOURCE — so whoever stopped a run can still read what it left behind.
         * @summary Stop what a sandbox is running, and keep the sandbox
         * @param {StopIn} stopIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async stopRun(stopIn: StopIn, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Stopped>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.stopRun(stopIn, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.stopRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Writes bytes to one path in the caller\'s sandbox, creating parents, and answers the resolved path.
         * @summary Write a file into a sandbox you hold
         * @param {WriteIn} writeIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async writeSandboxFile(writeIn: WriteIn, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Wrote>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.writeSandboxFile(writeIn, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.writeSandboxFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SandboxesApi - factory interface
 * @export
 */
export const SandboxesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SandboxesApiFp(configuration)
    return {
        /**
         * Stops the sandbox\'s pod and drops the lease. The VOLUME survives by default, so a `dev` or `desktop` sandbox can be leased again over the same project and find its checkout where it left it.  `purge=1` deletes the volume too. It is opt-in because it is the one part of this that cannot be undone.
         * @summary End a sandbox
         * @param {SandboxesApiDeleteV1SandboxesByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteV1SandboxesById(requestParameters: SandboxesApiDeleteV1SandboxesByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteV1SandboxesById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Ends the caller\'s sandbox lease: the pod goes, and the volume goes only when the caller asked for that too.
         * @summary End a sandbox and release it
         * @param {SandboxesApiEndSandboxRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        endSandbox(requestParameters: SandboxesApiEndSandboxRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.endSandbox(requestParameters.endIn, options).then((request) => request(axios, basePath));
        },
        /**
         * Lists the caller org\'s sandboxes, newest first. `project` and `status` narrow it, and both are read from the QUERY STRING.  It answers from the org\'s own store rather than from the cluster, so a sandbox whose pod has since died still appears, carrying the status it was last known to have. That is deliberate: a lease you are being charged for should not vanish from the list because the thing behind it fell over.
         * @summary The sandboxes this org holds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1Sandboxes(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getV1Sandboxes(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns one of the caller org\'s sandboxes. An id belonging to another org answers 404 and not 403 — a 403 would confirm the id exists, and whether a given sandbox exists is itself a cross-tenant fact.
         * @summary One sandbox
         * @param {SandboxesApiGetV1SandboxesByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1SandboxesById(requestParameters: SandboxesApiGetV1SandboxesByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getV1SandboxesById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Reads one file from the sandbox\'s project directory as text, or lists the entries when the path names a directory. Paths resolve under the project root and a path that climbs out is refused rather than rewritten.
         * @summary Read a file, or list a directory
         * @param {SandboxesApiGetV1SandboxesByIdFsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1SandboxesByIdFs(requestParameters: SandboxesApiGetV1SandboxesByIdFsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getV1SandboxesByIdFs(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * A complete, self-contained terminal — xterm inline, no other origin — that opens its own socket and runs a shell in this sandbox. Embed it in an iframe and there is nothing else to build.  `ticket` is the credential from the POST above and `arg` names the session (see the socket below); both are simply carried through to the socket. The page is NOT gated — it is inert markup and does not redeem the ticket, because a ticket is spent once and a page that spent it would hold a credential that no longer opens anything.  When the terminal is up it posts `{source:\"hanzo-term\", ready:true}` to its parent frame, so a host can tell a live terminal from a page that failed into something else. `frame-ancestors` admits our own brands\' hosts and nothing further.
         * @summary The terminal, as a page
         * @param {SandboxesApiGetV1SandboxesByIdTerminalRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1SandboxesByIdTerminal(requestParameters: SandboxesApiGetV1SandboxesByIdTerminalRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getV1SandboxesByIdTerminal(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Upgrades to a WebSocket carrying a login shell on a pseudo-terminal inside the sandbox — for a host that brings its own emulator. Requires `ticket`; a missing, expired or already-spent one answers 401 without upgrading.  THE WIRE. A text frame is stdin, unless it is the one control object `{\"resize\":{\"cols\":N,\"rows\":M}}`; a binary frame is always stdin. Output comes back as BINARY frames, because a pty emits arbitrary bytes cut at arbitrary offsets and a text frame carrying half a rune is one the browser closes the connection over.  `arg` names a SESSION: the shell runs under `tmux new -A -s <arg>`, which attaches to that session if it exists and creates it if it does not — so one sandbox holds as many terminals as a caller has names for. It is 1-64 characters of letters, digits, `-` or `_` and may not begin with `-`; anything else is 400. Without `arg` the shell is unnamed and unmultiplexed.  The shell is `zsh -l`, falling back to `bash -l` and then to `sh -l`, and to the plain shell again when the image has no tmux. Every step is a preference and none is a requirement: whatever else the image carries — the hanzo CLI included — is a command to type, never a condition for getting a prompt.
         * @summary The terminal, as a socket
         * @param {SandboxesApiGetV1SandboxesByIdTerminalWsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1SandboxesByIdTerminalWs(requestParameters: SandboxesApiGetV1SandboxesByIdTerminalWsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getV1SandboxesByIdTerminalWs(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Leases the caller\'s sandbox, or returns the one it named if that lease is still running.  What comes back is a real computer: a pod under a runtime boundary with a toolchain already in it, its own filesystem, and a lease that ends it. Every other op here acts on the one this returns.
         * @summary Lease a sandbox — a real computer — or resume one you hold
         * @param {SandboxesApiLeaseSandboxRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        leaseSandbox(requestParameters: SandboxesApiLeaseSandboxRequest, options?: RawAxiosRequestConfig): AxiosPromise<Leased> {
            return localVarFp.leaseSandbox(requestParameters.leaseIn, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a sandbox and returns it. `class` is one of `exec`, `dev` or `desktop`; `dev` and `desktop` are attached to a `project`, which is required for them and names the volume the work persists on. `ttlSec` bounds the lease, and `image` overrides the class default.  This is the ONLY path that creates cluster objects. The isolation boundary is the pod\'s runtime class, one field, so what a sandbox is confined by is a deployment decision rather than anything this operation negotiates.
         * @summary Lease a sandbox
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1Sandboxes(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postV1Sandboxes(options).then((request) => request(axios, basePath));
        },
        /**
         * Runs a command inside the sandbox and returns its exit code, stdout and stderr. A non-zero exit is a SUCCESSFUL call carrying a failed program — the HTTP status stays 200, because \"the tests failed\" and \"the sandbox is broken\" are different facts.  NOTHING RUNS IN cloud. The command is streamed to the Kubernetes exec subresource of the sandbox\'s pod, which runs under the gVisor runtime class. The sandbox is addressed by pod NAME through the apiserver, never by address.
         * @summary Run a command in a sandbox
         * @param {SandboxesApiPostV1SandboxesByIdExecRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1SandboxesByIdExec(requestParameters: SandboxesApiPostV1SandboxesByIdExecRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postV1SandboxesByIdExec(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Writes the request body to one file in the sandbox\'s project directory, creating parent directories. Same confinement as the read above.
         * @summary Write a file
         * @param {SandboxesApiPostV1SandboxesByIdFsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1SandboxesByIdFs(requestParameters: SandboxesApiPostV1SandboxesByIdFsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postV1SandboxesByIdFs(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Mints a SINGLE-USE ticket for one interactive terminal in this sandbox and returns `{ticket, expiresIn, url}`, where url is the terminal PAGE with the ticket already on it.  It exists because a browser carries no Authorization header into a WebSocket or an iframe, so a terminal cannot be authenticated the way every other route here is. The ticket is a credential MINTED for that one terminal: bound to this org and this sandbox, valid for thirty seconds, and gone the first time it is presented. A long-lived bearer in a query string would instead be written into every access log on the path.  Mint one per terminal, and mint a fresh one to reconnect.
         * @summary Open a terminal
         * @param {SandboxesApiPostV1SandboxesByIdTerminalTicketRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1SandboxesByIdTerminalTicket(requestParameters: SandboxesApiPostV1SandboxesByIdTerminalTicketRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postV1SandboxesByIdTerminalTicket(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Reads one path in the caller\'s sandbox: a file\'s bytes, or a directory\'s entries when the path names one.
         * @summary Read a file from a sandbox you hold
         * @param {SandboxesApiReadSandboxFileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readSandboxFile(requestParameters: SandboxesApiReadSandboxFileRequest, options?: RawAxiosRequestConfig): AxiosPromise<Blob> {
            return localVarFp.readSandboxFile(requestParameters.pathIn, options).then((request) => request(axios, basePath));
        },
        /**
         * Runs one command inside the caller\'s sandbox and answers its exit code, stdout and stderr. A non-zero exit is a successful call carrying a failed program, so it comes back as data and not as an error.  Name a `session` and the command NARRATES INTO IT: its output is appended to that session\'s live log as the program produces it, so anything watching the session — GET /v1/agents/sessions/stream, scoped to one run with ?root= — watches the work happen rather than waiting for the verdict. Without it the call is what it always was: silent until it returns, which for an agentic run is twenty-five minutes of blank screen.  The session is named; the TENANT is not. It is the org the caller already proved, so a session belonging to somebody else is absent from the org this call acts for and the append is refused there.
         * @summary Run a command in a sandbox you hold and read its output
         * @param {SandboxesApiRunInSandboxRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runInSandbox(requestParameters: SandboxesApiRunInSandboxRequest, options?: RawAxiosRequestConfig): AxiosPromise<Ran> {
            return localVarFp.runInSandbox(requestParameters.runIn, options).then((request) => request(axios, basePath));
        },
        /**
         * Interrupts whatever the caller\'s sandbox is running and answers how many commands it ended. The sandbox stays leased — stop ends the WORK, end ends the RESOURCE — so whoever stopped a run can still read what it left behind.
         * @summary Stop what a sandbox is running, and keep the sandbox
         * @param {SandboxesApiStopRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stopRun(requestParameters: SandboxesApiStopRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<Stopped> {
            return localVarFp.stopRun(requestParameters.stopIn, options).then((request) => request(axios, basePath));
        },
        /**
         * Writes bytes to one path in the caller\'s sandbox, creating parents, and answers the resolved path.
         * @summary Write a file into a sandbox you hold
         * @param {SandboxesApiWriteSandboxFileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        writeSandboxFile(requestParameters: SandboxesApiWriteSandboxFileRequest, options?: RawAxiosRequestConfig): AxiosPromise<Wrote> {
            return localVarFp.writeSandboxFile(requestParameters.writeIn, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteV1SandboxesById operation in SandboxesApi.
 * @export
 * @interface SandboxesApiDeleteV1SandboxesByIdRequest
 */
export interface SandboxesApiDeleteV1SandboxesByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof SandboxesApiDeleteV1SandboxesById
     */
    readonly id: string
}

/**
 * Request parameters for endSandbox operation in SandboxesApi.
 * @export
 * @interface SandboxesApiEndSandboxRequest
 */
export interface SandboxesApiEndSandboxRequest {
    /**
     * 
     * @type {EndIn}
     * @memberof SandboxesApiEndSandbox
     */
    readonly endIn: EndIn
}

/**
 * Request parameters for getV1SandboxesById operation in SandboxesApi.
 * @export
 * @interface SandboxesApiGetV1SandboxesByIdRequest
 */
export interface SandboxesApiGetV1SandboxesByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof SandboxesApiGetV1SandboxesById
     */
    readonly id: string
}

/**
 * Request parameters for getV1SandboxesByIdFs operation in SandboxesApi.
 * @export
 * @interface SandboxesApiGetV1SandboxesByIdFsRequest
 */
export interface SandboxesApiGetV1SandboxesByIdFsRequest {
    /**
     * 
     * @type {string}
     * @memberof SandboxesApiGetV1SandboxesByIdFs
     */
    readonly id: string
}

/**
 * Request parameters for getV1SandboxesByIdTerminal operation in SandboxesApi.
 * @export
 * @interface SandboxesApiGetV1SandboxesByIdTerminalRequest
 */
export interface SandboxesApiGetV1SandboxesByIdTerminalRequest {
    /**
     * 
     * @type {string}
     * @memberof SandboxesApiGetV1SandboxesByIdTerminal
     */
    readonly id: string
}

/**
 * Request parameters for getV1SandboxesByIdTerminalWs operation in SandboxesApi.
 * @export
 * @interface SandboxesApiGetV1SandboxesByIdTerminalWsRequest
 */
export interface SandboxesApiGetV1SandboxesByIdTerminalWsRequest {
    /**
     * 
     * @type {string}
     * @memberof SandboxesApiGetV1SandboxesByIdTerminalWs
     */
    readonly id: string
}

/**
 * Request parameters for leaseSandbox operation in SandboxesApi.
 * @export
 * @interface SandboxesApiLeaseSandboxRequest
 */
export interface SandboxesApiLeaseSandboxRequest {
    /**
     * 
     * @type {LeaseIn}
     * @memberof SandboxesApiLeaseSandbox
     */
    readonly leaseIn: LeaseIn
}

/**
 * Request parameters for postV1SandboxesByIdExec operation in SandboxesApi.
 * @export
 * @interface SandboxesApiPostV1SandboxesByIdExecRequest
 */
export interface SandboxesApiPostV1SandboxesByIdExecRequest {
    /**
     * 
     * @type {string}
     * @memberof SandboxesApiPostV1SandboxesByIdExec
     */
    readonly id: string
}

/**
 * Request parameters for postV1SandboxesByIdFs operation in SandboxesApi.
 * @export
 * @interface SandboxesApiPostV1SandboxesByIdFsRequest
 */
export interface SandboxesApiPostV1SandboxesByIdFsRequest {
    /**
     * 
     * @type {string}
     * @memberof SandboxesApiPostV1SandboxesByIdFs
     */
    readonly id: string
}

/**
 * Request parameters for postV1SandboxesByIdTerminalTicket operation in SandboxesApi.
 * @export
 * @interface SandboxesApiPostV1SandboxesByIdTerminalTicketRequest
 */
export interface SandboxesApiPostV1SandboxesByIdTerminalTicketRequest {
    /**
     * 
     * @type {string}
     * @memberof SandboxesApiPostV1SandboxesByIdTerminalTicket
     */
    readonly id: string
}

/**
 * Request parameters for readSandboxFile operation in SandboxesApi.
 * @export
 * @interface SandboxesApiReadSandboxFileRequest
 */
export interface SandboxesApiReadSandboxFileRequest {
    /**
     * 
     * @type {PathIn}
     * @memberof SandboxesApiReadSandboxFile
     */
    readonly pathIn: PathIn
}

/**
 * Request parameters for runInSandbox operation in SandboxesApi.
 * @export
 * @interface SandboxesApiRunInSandboxRequest
 */
export interface SandboxesApiRunInSandboxRequest {
    /**
     * 
     * @type {RunIn}
     * @memberof SandboxesApiRunInSandbox
     */
    readonly runIn: RunIn
}

/**
 * Request parameters for stopRun operation in SandboxesApi.
 * @export
 * @interface SandboxesApiStopRunRequest
 */
export interface SandboxesApiStopRunRequest {
    /**
     * 
     * @type {StopIn}
     * @memberof SandboxesApiStopRun
     */
    readonly stopIn: StopIn
}

/**
 * Request parameters for writeSandboxFile operation in SandboxesApi.
 * @export
 * @interface SandboxesApiWriteSandboxFileRequest
 */
export interface SandboxesApiWriteSandboxFileRequest {
    /**
     * 
     * @type {WriteIn}
     * @memberof SandboxesApiWriteSandboxFile
     */
    readonly writeIn: WriteIn
}

/**
 * SandboxesApi - object-oriented interface
 * @export
 * @class SandboxesApi
 * @extends {BaseAPI}
 */
export class SandboxesApi extends BaseAPI {
    /**
     * Stops the sandbox\'s pod and drops the lease. The VOLUME survives by default, so a `dev` or `desktop` sandbox can be leased again over the same project and find its checkout where it left it.  `purge=1` deletes the volume too. It is opt-in because it is the one part of this that cannot be undone.
     * @summary End a sandbox
     * @param {SandboxesApiDeleteV1SandboxesByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public deleteV1SandboxesById(requestParameters: SandboxesApiDeleteV1SandboxesByIdRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).deleteV1SandboxesById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Ends the caller\'s sandbox lease: the pod goes, and the volume goes only when the caller asked for that too.
     * @summary End a sandbox and release it
     * @param {SandboxesApiEndSandboxRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public endSandbox(requestParameters: SandboxesApiEndSandboxRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).endSandbox(requestParameters.endIn, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lists the caller org\'s sandboxes, newest first. `project` and `status` narrow it, and both are read from the QUERY STRING.  It answers from the org\'s own store rather than from the cluster, so a sandbox whose pod has since died still appears, carrying the status it was last known to have. That is deliberate: a lease you are being charged for should not vanish from the list because the thing behind it fell over.
     * @summary The sandboxes this org holds
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public getV1Sandboxes(options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).getV1Sandboxes(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns one of the caller org\'s sandboxes. An id belonging to another org answers 404 and not 403 — a 403 would confirm the id exists, and whether a given sandbox exists is itself a cross-tenant fact.
     * @summary One sandbox
     * @param {SandboxesApiGetV1SandboxesByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public getV1SandboxesById(requestParameters: SandboxesApiGetV1SandboxesByIdRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).getV1SandboxesById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Reads one file from the sandbox\'s project directory as text, or lists the entries when the path names a directory. Paths resolve under the project root and a path that climbs out is refused rather than rewritten.
     * @summary Read a file, or list a directory
     * @param {SandboxesApiGetV1SandboxesByIdFsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public getV1SandboxesByIdFs(requestParameters: SandboxesApiGetV1SandboxesByIdFsRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).getV1SandboxesByIdFs(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * A complete, self-contained terminal — xterm inline, no other origin — that opens its own socket and runs a shell in this sandbox. Embed it in an iframe and there is nothing else to build.  `ticket` is the credential from the POST above and `arg` names the session (see the socket below); both are simply carried through to the socket. The page is NOT gated — it is inert markup and does not redeem the ticket, because a ticket is spent once and a page that spent it would hold a credential that no longer opens anything.  When the terminal is up it posts `{source:\"hanzo-term\", ready:true}` to its parent frame, so a host can tell a live terminal from a page that failed into something else. `frame-ancestors` admits our own brands\' hosts and nothing further.
     * @summary The terminal, as a page
     * @param {SandboxesApiGetV1SandboxesByIdTerminalRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public getV1SandboxesByIdTerminal(requestParameters: SandboxesApiGetV1SandboxesByIdTerminalRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).getV1SandboxesByIdTerminal(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Upgrades to a WebSocket carrying a login shell on a pseudo-terminal inside the sandbox — for a host that brings its own emulator. Requires `ticket`; a missing, expired or already-spent one answers 401 without upgrading.  THE WIRE. A text frame is stdin, unless it is the one control object `{\"resize\":{\"cols\":N,\"rows\":M}}`; a binary frame is always stdin. Output comes back as BINARY frames, because a pty emits arbitrary bytes cut at arbitrary offsets and a text frame carrying half a rune is one the browser closes the connection over.  `arg` names a SESSION: the shell runs under `tmux new -A -s <arg>`, which attaches to that session if it exists and creates it if it does not — so one sandbox holds as many terminals as a caller has names for. It is 1-64 characters of letters, digits, `-` or `_` and may not begin with `-`; anything else is 400. Without `arg` the shell is unnamed and unmultiplexed.  The shell is `zsh -l`, falling back to `bash -l` and then to `sh -l`, and to the plain shell again when the image has no tmux. Every step is a preference and none is a requirement: whatever else the image carries — the hanzo CLI included — is a command to type, never a condition for getting a prompt.
     * @summary The terminal, as a socket
     * @param {SandboxesApiGetV1SandboxesByIdTerminalWsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public getV1SandboxesByIdTerminalWs(requestParameters: SandboxesApiGetV1SandboxesByIdTerminalWsRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).getV1SandboxesByIdTerminalWs(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Leases the caller\'s sandbox, or returns the one it named if that lease is still running.  What comes back is a real computer: a pod under a runtime boundary with a toolchain already in it, its own filesystem, and a lease that ends it. Every other op here acts on the one this returns.
     * @summary Lease a sandbox — a real computer — or resume one you hold
     * @param {SandboxesApiLeaseSandboxRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public leaseSandbox(requestParameters: SandboxesApiLeaseSandboxRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).leaseSandbox(requestParameters.leaseIn, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a sandbox and returns it. `class` is one of `exec`, `dev` or `desktop`; `dev` and `desktop` are attached to a `project`, which is required for them and names the volume the work persists on. `ttlSec` bounds the lease, and `image` overrides the class default.  This is the ONLY path that creates cluster objects. The isolation boundary is the pod\'s runtime class, one field, so what a sandbox is confined by is a deployment decision rather than anything this operation negotiates.
     * @summary Lease a sandbox
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public postV1Sandboxes(options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).postV1Sandboxes(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Runs a command inside the sandbox and returns its exit code, stdout and stderr. A non-zero exit is a SUCCESSFUL call carrying a failed program — the HTTP status stays 200, because \"the tests failed\" and \"the sandbox is broken\" are different facts.  NOTHING RUNS IN cloud. The command is streamed to the Kubernetes exec subresource of the sandbox\'s pod, which runs under the gVisor runtime class. The sandbox is addressed by pod NAME through the apiserver, never by address.
     * @summary Run a command in a sandbox
     * @param {SandboxesApiPostV1SandboxesByIdExecRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public postV1SandboxesByIdExec(requestParameters: SandboxesApiPostV1SandboxesByIdExecRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).postV1SandboxesByIdExec(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Writes the request body to one file in the sandbox\'s project directory, creating parent directories. Same confinement as the read above.
     * @summary Write a file
     * @param {SandboxesApiPostV1SandboxesByIdFsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public postV1SandboxesByIdFs(requestParameters: SandboxesApiPostV1SandboxesByIdFsRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).postV1SandboxesByIdFs(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Mints a SINGLE-USE ticket for one interactive terminal in this sandbox and returns `{ticket, expiresIn, url}`, where url is the terminal PAGE with the ticket already on it.  It exists because a browser carries no Authorization header into a WebSocket or an iframe, so a terminal cannot be authenticated the way every other route here is. The ticket is a credential MINTED for that one terminal: bound to this org and this sandbox, valid for thirty seconds, and gone the first time it is presented. A long-lived bearer in a query string would instead be written into every access log on the path.  Mint one per terminal, and mint a fresh one to reconnect.
     * @summary Open a terminal
     * @param {SandboxesApiPostV1SandboxesByIdTerminalTicketRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public postV1SandboxesByIdTerminalTicket(requestParameters: SandboxesApiPostV1SandboxesByIdTerminalTicketRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).postV1SandboxesByIdTerminalTicket(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Reads one path in the caller\'s sandbox: a file\'s bytes, or a directory\'s entries when the path names one.
     * @summary Read a file from a sandbox you hold
     * @param {SandboxesApiReadSandboxFileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public readSandboxFile(requestParameters: SandboxesApiReadSandboxFileRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).readSandboxFile(requestParameters.pathIn, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Runs one command inside the caller\'s sandbox and answers its exit code, stdout and stderr. A non-zero exit is a successful call carrying a failed program, so it comes back as data and not as an error.  Name a `session` and the command NARRATES INTO IT: its output is appended to that session\'s live log as the program produces it, so anything watching the session — GET /v1/agents/sessions/stream, scoped to one run with ?root= — watches the work happen rather than waiting for the verdict. Without it the call is what it always was: silent until it returns, which for an agentic run is twenty-five minutes of blank screen.  The session is named; the TENANT is not. It is the org the caller already proved, so a session belonging to somebody else is absent from the org this call acts for and the append is refused there.
     * @summary Run a command in a sandbox you hold and read its output
     * @param {SandboxesApiRunInSandboxRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public runInSandbox(requestParameters: SandboxesApiRunInSandboxRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).runInSandbox(requestParameters.runIn, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Interrupts whatever the caller\'s sandbox is running and answers how many commands it ended. The sandbox stays leased — stop ends the WORK, end ends the RESOURCE — so whoever stopped a run can still read what it left behind.
     * @summary Stop what a sandbox is running, and keep the sandbox
     * @param {SandboxesApiStopRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public stopRun(requestParameters: SandboxesApiStopRunRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).stopRun(requestParameters.stopIn, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Writes bytes to one path in the caller\'s sandbox, creating parents, and answers the resolved path.
     * @summary Write a file into a sandbox you hold
     * @param {SandboxesApiWriteSandboxFileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SandboxesApi
     */
    public writeSandboxFile(requestParameters: SandboxesApiWriteSandboxFileRequest, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).writeSandboxFile(requestParameters.writeIn, options).then((request) => request(this.axios, this.basePath));
    }
}

