/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { StreamConsumeMessages200Response } from '../models';
// @ts-ignore
import type { StreamProduceRequest } from '../models';
// @ts-ignore
import type { StreamProduceResponse } from '../models';
/**
 * StreamMessagesApi - axios parameter creator
 * @export
 */
export const StreamMessagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Consume messages from a topic partition via REST API. For persistent consumption, use the Kafka wire protocol with consumer groups. 
         * @summary Consume messages
         * @param {string} topic 
         * @param {number} [partition] Partition to consume from
         * @param {string} [offset] Starting offset (earliest, latest, or numeric offset)
         * @param {number} [limit] Maximum records to return
         * @param {number} [timeout] Long-poll timeout in milliseconds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        streamConsumeMessages: async (topic: string, partition?: number, offset?: string, limit?: number, timeout?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'topic' is not null or undefined
            assertParamExists('streamConsumeMessages', 'topic', topic)
            const localVarPath = `/v1/stream/topics/{topic}/messages`
                .replace(`{${"topic"}}`, encodeURIComponent(String(topic)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (partition !== undefined) {
                localVarQueryParameter['partition'] = partition;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (timeout !== undefined) {
                localVarQueryParameter['timeout'] = timeout;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Produce one or more messages to a topic via REST API. For high throughput, use the Kafka wire protocol on port 9092. 
         * @summary Produce messages
         * @param {string} topic 
         * @param {StreamProduceRequest} streamProduceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        streamProduceMessages: async (topic: string, streamProduceRequest: StreamProduceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'topic' is not null or undefined
            assertParamExists('streamProduceMessages', 'topic', topic)
            // verify required parameter 'streamProduceRequest' is not null or undefined
            assertParamExists('streamProduceMessages', 'streamProduceRequest', streamProduceRequest)
            const localVarPath = `/v1/stream/topics/{topic}/messages`
                .replace(`{${"topic"}}`, encodeURIComponent(String(topic)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(streamProduceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StreamMessagesApi - functional programming interface
 * @export
 */
export const StreamMessagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StreamMessagesApiAxiosParamCreator(configuration)
    return {
        /**
         * Consume messages from a topic partition via REST API. For persistent consumption, use the Kafka wire protocol with consumer groups. 
         * @summary Consume messages
         * @param {string} topic 
         * @param {number} [partition] Partition to consume from
         * @param {string} [offset] Starting offset (earliest, latest, or numeric offset)
         * @param {number} [limit] Maximum records to return
         * @param {number} [timeout] Long-poll timeout in milliseconds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async streamConsumeMessages(topic: string, partition?: number, offset?: string, limit?: number, timeout?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StreamConsumeMessages200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.streamConsumeMessages(topic, partition, offset, limit, timeout, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StreamMessagesApi.streamConsumeMessages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Produce one or more messages to a topic via REST API. For high throughput, use the Kafka wire protocol on port 9092. 
         * @summary Produce messages
         * @param {string} topic 
         * @param {StreamProduceRequest} streamProduceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async streamProduceMessages(topic: string, streamProduceRequest: StreamProduceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StreamProduceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.streamProduceMessages(topic, streamProduceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StreamMessagesApi.streamProduceMessages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StreamMessagesApi - factory interface
 * @export
 */
export const StreamMessagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StreamMessagesApiFp(configuration)
    return {
        /**
         * Consume messages from a topic partition via REST API. For persistent consumption, use the Kafka wire protocol with consumer groups. 
         * @summary Consume messages
         * @param {StreamMessagesApiStreamConsumeMessagesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        streamConsumeMessages(requestParameters: StreamMessagesApiStreamConsumeMessagesRequest, options?: RawAxiosRequestConfig): AxiosPromise<StreamConsumeMessages200Response> {
            return localVarFp.streamConsumeMessages(requestParameters.topic, requestParameters.partition, requestParameters.offset, requestParameters.limit, requestParameters.timeout, options).then((request) => request(axios, basePath));
        },
        /**
         * Produce one or more messages to a topic via REST API. For high throughput, use the Kafka wire protocol on port 9092. 
         * @summary Produce messages
         * @param {StreamMessagesApiStreamProduceMessagesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        streamProduceMessages(requestParameters: StreamMessagesApiStreamProduceMessagesRequest, options?: RawAxiosRequestConfig): AxiosPromise<StreamProduceResponse> {
            return localVarFp.streamProduceMessages(requestParameters.topic, requestParameters.streamProduceRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for streamConsumeMessages operation in StreamMessagesApi.
 * @export
 * @interface StreamMessagesApiStreamConsumeMessagesRequest
 */
export interface StreamMessagesApiStreamConsumeMessagesRequest {
    /**
     * 
     * @type {string}
     * @memberof StreamMessagesApiStreamConsumeMessages
     */
    readonly topic: string

    /**
     * Partition to consume from
     * @type {number}
     * @memberof StreamMessagesApiStreamConsumeMessages
     */
    readonly partition?: number

    /**
     * Starting offset (earliest, latest, or numeric offset)
     * @type {string}
     * @memberof StreamMessagesApiStreamConsumeMessages
     */
    readonly offset?: string

    /**
     * Maximum records to return
     * @type {number}
     * @memberof StreamMessagesApiStreamConsumeMessages
     */
    readonly limit?: number

    /**
     * Long-poll timeout in milliseconds
     * @type {number}
     * @memberof StreamMessagesApiStreamConsumeMessages
     */
    readonly timeout?: number
}

/**
 * Request parameters for streamProduceMessages operation in StreamMessagesApi.
 * @export
 * @interface StreamMessagesApiStreamProduceMessagesRequest
 */
export interface StreamMessagesApiStreamProduceMessagesRequest {
    /**
     * 
     * @type {string}
     * @memberof StreamMessagesApiStreamProduceMessages
     */
    readonly topic: string

    /**
     * 
     * @type {StreamProduceRequest}
     * @memberof StreamMessagesApiStreamProduceMessages
     */
    readonly streamProduceRequest: StreamProduceRequest
}

/**
 * StreamMessagesApi - object-oriented interface
 * @export
 * @class StreamMessagesApi
 * @extends {BaseAPI}
 */
export class StreamMessagesApi extends BaseAPI {
    /**
     * Consume messages from a topic partition via REST API. For persistent consumption, use the Kafka wire protocol with consumer groups. 
     * @summary Consume messages
     * @param {StreamMessagesApiStreamConsumeMessagesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StreamMessagesApi
     */
    public streamConsumeMessages(requestParameters: StreamMessagesApiStreamConsumeMessagesRequest, options?: RawAxiosRequestConfig) {
        return StreamMessagesApiFp(this.configuration).streamConsumeMessages(requestParameters.topic, requestParameters.partition, requestParameters.offset, requestParameters.limit, requestParameters.timeout, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Produce one or more messages to a topic via REST API. For high throughput, use the Kafka wire protocol on port 9092. 
     * @summary Produce messages
     * @param {StreamMessagesApiStreamProduceMessagesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StreamMessagesApi
     */
    public streamProduceMessages(requestParameters: StreamMessagesApiStreamProduceMessagesRequest, options?: RawAxiosRequestConfig) {
        return StreamMessagesApiFp(this.configuration).streamProduceMessages(requestParameters.topic, requestParameters.streamProduceRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

