/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud\'s own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CloudProvisionRequest } from '../models';
// @ts-ignore
import type { CloudProvisionResult } from '../models';
// @ts-ignore
import type { CloudProvisionedResource } from '../models';
// @ts-ignore
import type { CloudProvisionedSummary } from '../models';
// @ts-ignore
import type { CloudVectorCollectionList } from '../models';
// @ts-ignore
import type { CloudVectorStats } from '../models';
/**
 * VectorApi - axios parameter creator
 * @export
 */
export const VectorApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * DropVector deletes one vector collection from the shared backend and removes its metadata row. Answers 204 with no body; a second call is a 404.
         * @summary DropVector deletes one vector collection from the shared backend and removes its metadata row.
         * @param {string} name Name is the resource\&#39;s org-unique slug, from the path. Lower-cased and trimmed before lookup, exactly as it was at create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudDeleteV1VectorName: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('cloudDeleteV1VectorName', 'name', name)
            const localVarPath = `/v1/vector/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ListVector lists the caller org\'s vector collections. A collection is a logical resource inside an already-live shared backend, so every one of them is reached through the public gateway rather than at an instance of its own.
         * @summary ListVector lists the caller org\'s vector collections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1Vector: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/vector`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lists the vector collections with their size and geometry.  It reads the in-cluster Qdrant service: the collection list, then each collection\'s detail for its point count, vector dimension and distance metric. Per-collection detail is best-effort — one collection that fails to describe itself keeps its name and defaults (dimension 0, cosine) rather than blanking the whole panel — and an unreachable Qdrant answers 200 with an EMPTY list.
         * @summary Lists the vector collections with their size and geometry.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1VectorCollections: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/vector/collections`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * GetVector returns one vector collection\'s metadata. It carries the collection\'s status and the gateway address it is reached at, and no username: the backend authenticates with a shared, out-of-band key rather than a per-collection credential, so there is no per-resource user to report.
         * @summary GetVector returns one vector collection\'s metadata.
         * @param {string} name Name is the resource\&#39;s org-unique slug, from the path. Lower-cased and trimmed before lookup, exactly as it was at create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1VectorName: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('cloudGetV1VectorName', 'name', name)
            const localVarPath = `/v1/vector/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Totals the collections, vectors and storage across the vector store.  Every figure is summed from the same per-collection detail GET /v1/vector/collections returns, so the two panels can never disagree. An unreachable Qdrant answers 200 with all zeros rather than an error.
         * @summary Totals the collections, vectors and storage across the vector store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1VectorStats: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/vector/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CloudProvisionRequest} [cloudProvisionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPostV1Vector: async (cloudProvisionRequest?: CloudProvisionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/vector`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cloudProvisionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VectorApi - functional programming interface
 * @export
 */
export const VectorApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VectorApiAxiosParamCreator(configuration)
    return {
        /**
         * DropVector deletes one vector collection from the shared backend and removes its metadata row. Answers 204 with no body; a second call is a 404.
         * @summary DropVector deletes one vector collection from the shared backend and removes its metadata row.
         * @param {string} name Name is the resource\&#39;s org-unique slug, from the path. Lower-cased and trimmed before lookup, exactly as it was at create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudDeleteV1VectorName(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudDeleteV1VectorName(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VectorApi.cloudDeleteV1VectorName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ListVector lists the caller org\'s vector collections. A collection is a logical resource inside an already-live shared backend, so every one of them is reached through the public gateway rather than at an instance of its own.
         * @summary ListVector lists the caller org\'s vector collections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudGetV1Vector(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CloudProvisionedSummary>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudGetV1Vector(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VectorApi.cloudGetV1Vector']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lists the vector collections with their size and geometry.  It reads the in-cluster Qdrant service: the collection list, then each collection\'s detail for its point count, vector dimension and distance metric. Per-collection detail is best-effort — one collection that fails to describe itself keeps its name and defaults (dimension 0, cosine) rather than blanking the whole panel — and an unreachable Qdrant answers 200 with an EMPTY list.
         * @summary Lists the vector collections with their size and geometry.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudGetV1VectorCollections(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudVectorCollectionList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudGetV1VectorCollections(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VectorApi.cloudGetV1VectorCollections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * GetVector returns one vector collection\'s metadata. It carries the collection\'s status and the gateway address it is reached at, and no username: the backend authenticates with a shared, out-of-band key rather than a per-collection credential, so there is no per-resource user to report.
         * @summary GetVector returns one vector collection\'s metadata.
         * @param {string} name Name is the resource\&#39;s org-unique slug, from the path. Lower-cased and trimmed before lookup, exactly as it was at create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudGetV1VectorName(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudProvisionedResource>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudGetV1VectorName(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VectorApi.cloudGetV1VectorName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Totals the collections, vectors and storage across the vector store.  Every figure is summed from the same per-collection detail GET /v1/vector/collections returns, so the two panels can never disagree. An unreachable Qdrant answers 200 with all zeros rather than an error.
         * @summary Totals the collections, vectors and storage across the vector store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudGetV1VectorStats(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudVectorStats>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudGetV1VectorStats(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VectorApi.cloudGetV1VectorStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CloudProvisionRequest} [cloudProvisionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cloudPostV1Vector(cloudProvisionRequest?: CloudProvisionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloudProvisionResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cloudPostV1Vector(cloudProvisionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VectorApi.cloudPostV1Vector']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VectorApi - factory interface
 * @export
 */
export const VectorApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VectorApiFp(configuration)
    return {
        /**
         * DropVector deletes one vector collection from the shared backend and removes its metadata row. Answers 204 with no body; a second call is a 404.
         * @summary DropVector deletes one vector collection from the shared backend and removes its metadata row.
         * @param {VectorApiCloudDeleteV1VectorNameRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudDeleteV1VectorName(requestParameters: VectorApiCloudDeleteV1VectorNameRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cloudDeleteV1VectorName(requestParameters.name, options).then((request) => request(axios, basePath));
        },
        /**
         * ListVector lists the caller org\'s vector collections. A collection is a logical resource inside an already-live shared backend, so every one of them is reached through the public gateway rather than at an instance of its own.
         * @summary ListVector lists the caller org\'s vector collections.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1Vector(options?: RawAxiosRequestConfig): AxiosPromise<Array<CloudProvisionedSummary>> {
            return localVarFp.cloudGetV1Vector(options).then((request) => request(axios, basePath));
        },
        /**
         * Lists the vector collections with their size and geometry.  It reads the in-cluster Qdrant service: the collection list, then each collection\'s detail for its point count, vector dimension and distance metric. Per-collection detail is best-effort — one collection that fails to describe itself keeps its name and defaults (dimension 0, cosine) rather than blanking the whole panel — and an unreachable Qdrant answers 200 with an EMPTY list.
         * @summary Lists the vector collections with their size and geometry.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1VectorCollections(options?: RawAxiosRequestConfig): AxiosPromise<CloudVectorCollectionList> {
            return localVarFp.cloudGetV1VectorCollections(options).then((request) => request(axios, basePath));
        },
        /**
         * GetVector returns one vector collection\'s metadata. It carries the collection\'s status and the gateway address it is reached at, and no username: the backend authenticates with a shared, out-of-band key rather than a per-collection credential, so there is no per-resource user to report.
         * @summary GetVector returns one vector collection\'s metadata.
         * @param {VectorApiCloudGetV1VectorNameRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1VectorName(requestParameters: VectorApiCloudGetV1VectorNameRequest, options?: RawAxiosRequestConfig): AxiosPromise<CloudProvisionedResource> {
            return localVarFp.cloudGetV1VectorName(requestParameters.name, options).then((request) => request(axios, basePath));
        },
        /**
         * Totals the collections, vectors and storage across the vector store.  Every figure is summed from the same per-collection detail GET /v1/vector/collections returns, so the two panels can never disagree. An unreachable Qdrant answers 200 with all zeros rather than an error.
         * @summary Totals the collections, vectors and storage across the vector store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudGetV1VectorStats(options?: RawAxiosRequestConfig): AxiosPromise<CloudVectorStats> {
            return localVarFp.cloudGetV1VectorStats(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {VectorApiCloudPostV1VectorRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cloudPostV1Vector(requestParameters: VectorApiCloudPostV1VectorRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CloudProvisionResult> {
            return localVarFp.cloudPostV1Vector(requestParameters.cloudProvisionRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for cloudDeleteV1VectorName operation in VectorApi.
 * @export
 * @interface VectorApiCloudDeleteV1VectorNameRequest
 */
export interface VectorApiCloudDeleteV1VectorNameRequest {
    /**
     * Name is the resource\&#39;s org-unique slug, from the path. Lower-cased and trimmed before lookup, exactly as it was at create.
     * @type {string}
     * @memberof VectorApiCloudDeleteV1VectorName
     */
    readonly name: string
}

/**
 * Request parameters for cloudGetV1VectorName operation in VectorApi.
 * @export
 * @interface VectorApiCloudGetV1VectorNameRequest
 */
export interface VectorApiCloudGetV1VectorNameRequest {
    /**
     * Name is the resource\&#39;s org-unique slug, from the path. Lower-cased and trimmed before lookup, exactly as it was at create.
     * @type {string}
     * @memberof VectorApiCloudGetV1VectorName
     */
    readonly name: string
}

/**
 * Request parameters for cloudPostV1Vector operation in VectorApi.
 * @export
 * @interface VectorApiCloudPostV1VectorRequest
 */
export interface VectorApiCloudPostV1VectorRequest {
    /**
     * 
     * @type {CloudProvisionRequest}
     * @memberof VectorApiCloudPostV1Vector
     */
    readonly cloudProvisionRequest?: CloudProvisionRequest
}

/**
 * VectorApi - object-oriented interface
 * @export
 * @class VectorApi
 * @extends {BaseAPI}
 */
export class VectorApi extends BaseAPI {
    /**
     * DropVector deletes one vector collection from the shared backend and removes its metadata row. Answers 204 with no body; a second call is a 404.
     * @summary DropVector deletes one vector collection from the shared backend and removes its metadata row.
     * @param {VectorApiCloudDeleteV1VectorNameRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VectorApi
     */
    public cloudDeleteV1VectorName(requestParameters: VectorApiCloudDeleteV1VectorNameRequest, options?: RawAxiosRequestConfig) {
        return VectorApiFp(this.configuration).cloudDeleteV1VectorName(requestParameters.name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ListVector lists the caller org\'s vector collections. A collection is a logical resource inside an already-live shared backend, so every one of them is reached through the public gateway rather than at an instance of its own.
     * @summary ListVector lists the caller org\'s vector collections.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VectorApi
     */
    public cloudGetV1Vector(options?: RawAxiosRequestConfig) {
        return VectorApiFp(this.configuration).cloudGetV1Vector(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lists the vector collections with their size and geometry.  It reads the in-cluster Qdrant service: the collection list, then each collection\'s detail for its point count, vector dimension and distance metric. Per-collection detail is best-effort — one collection that fails to describe itself keeps its name and defaults (dimension 0, cosine) rather than blanking the whole panel — and an unreachable Qdrant answers 200 with an EMPTY list.
     * @summary Lists the vector collections with their size and geometry.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VectorApi
     */
    public cloudGetV1VectorCollections(options?: RawAxiosRequestConfig) {
        return VectorApiFp(this.configuration).cloudGetV1VectorCollections(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * GetVector returns one vector collection\'s metadata. It carries the collection\'s status and the gateway address it is reached at, and no username: the backend authenticates with a shared, out-of-band key rather than a per-collection credential, so there is no per-resource user to report.
     * @summary GetVector returns one vector collection\'s metadata.
     * @param {VectorApiCloudGetV1VectorNameRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VectorApi
     */
    public cloudGetV1VectorName(requestParameters: VectorApiCloudGetV1VectorNameRequest, options?: RawAxiosRequestConfig) {
        return VectorApiFp(this.configuration).cloudGetV1VectorName(requestParameters.name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Totals the collections, vectors and storage across the vector store.  Every figure is summed from the same per-collection detail GET /v1/vector/collections returns, so the two panels can never disagree. An unreachable Qdrant answers 200 with all zeros rather than an error.
     * @summary Totals the collections, vectors and storage across the vector store.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VectorApi
     */
    public cloudGetV1VectorStats(options?: RawAxiosRequestConfig) {
        return VectorApiFp(this.configuration).cloudGetV1VectorStats(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {VectorApiCloudPostV1VectorRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VectorApi
     */
    public cloudPostV1Vector(requestParameters: VectorApiCloudPostV1VectorRequest = {}, options?: RawAxiosRequestConfig) {
        return VectorApiFp(this.configuration).cloudPostV1Vector(requestParameters.cloudProvisionRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

