/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { InlineObject } from '../models';
// @ts-ignore
import type { VisorAgentBinding } from '../models';
// @ts-ignore
import type { VisorBindAgentRequest } from '../models';
// @ts-ignore
import type { VisorListAgentBindings200Response } from '../models';
/**
 * VisorBindingsApi - axios parameter creator
 * @export
 */
export const VisorBindingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Bind a cloud Agent to a machine
         * @param {string} id 
         * @param {VisorBindAgentRequest} visorBindAgentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        visorBindMachineAgent: async (id: string, visorBindAgentRequest: VisorBindAgentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('visorBindMachineAgent', 'id', id)
            // verify required parameter 'visorBindAgentRequest' is not null or undefined
            assertParamExists('visorBindMachineAgent', 'visorBindAgentRequest', visorBindAgentRequest)
            const localVarPath = `/v1/machines/{id}/bind-agent`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(visorBindAgentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a machine\'s agent binding
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        visorGetMachineAgentBinding: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('visorGetMachineAgentBinding', 'id', id)
            const localVarPath = `/v1/machines/{id}/agent-binding`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List the org\'s agent bindings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        visorListAgentBindings: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/agent-bindings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Unbind the agent from a machine
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        visorUnbindMachineAgent: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('visorUnbindMachineAgent', 'id', id)
            const localVarPath = `/v1/machines/{id}/agent-binding`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VisorBindingsApi - functional programming interface
 * @export
 */
export const VisorBindingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VisorBindingsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Bind a cloud Agent to a machine
         * @param {string} id 
         * @param {VisorBindAgentRequest} visorBindAgentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async visorBindMachineAgent(id: string, visorBindAgentRequest: VisorBindAgentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VisorAgentBinding>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.visorBindMachineAgent(id, visorBindAgentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VisorBindingsApi.visorBindMachineAgent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a machine\'s agent binding
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async visorGetMachineAgentBinding(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VisorAgentBinding>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.visorGetMachineAgentBinding(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VisorBindingsApi.visorGetMachineAgentBinding']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List the org\'s agent bindings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async visorListAgentBindings(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VisorListAgentBindings200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.visorListAgentBindings(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VisorBindingsApi.visorListAgentBindings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Unbind the agent from a machine
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async visorUnbindMachineAgent(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.visorUnbindMachineAgent(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VisorBindingsApi.visorUnbindMachineAgent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VisorBindingsApi - factory interface
 * @export
 */
export const VisorBindingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VisorBindingsApiFp(configuration)
    return {
        /**
         * 
         * @summary Bind a cloud Agent to a machine
         * @param {VisorBindingsApiVisorBindMachineAgentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        visorBindMachineAgent(requestParameters: VisorBindingsApiVisorBindMachineAgentRequest, options?: RawAxiosRequestConfig): AxiosPromise<VisorAgentBinding> {
            return localVarFp.visorBindMachineAgent(requestParameters.id, requestParameters.visorBindAgentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a machine\'s agent binding
         * @param {VisorBindingsApiVisorGetMachineAgentBindingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        visorGetMachineAgentBinding(requestParameters: VisorBindingsApiVisorGetMachineAgentBindingRequest, options?: RawAxiosRequestConfig): AxiosPromise<VisorAgentBinding> {
            return localVarFp.visorGetMachineAgentBinding(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List the org\'s agent bindings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        visorListAgentBindings(options?: RawAxiosRequestConfig): AxiosPromise<VisorListAgentBindings200Response> {
            return localVarFp.visorListAgentBindings(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Unbind the agent from a machine
         * @param {VisorBindingsApiVisorUnbindMachineAgentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        visorUnbindMachineAgent(requestParameters: VisorBindingsApiVisorUnbindMachineAgentRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.visorUnbindMachineAgent(requestParameters.id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for visorBindMachineAgent operation in VisorBindingsApi.
 * @export
 * @interface VisorBindingsApiVisorBindMachineAgentRequest
 */
export interface VisorBindingsApiVisorBindMachineAgentRequest {
    /**
     * 
     * @type {string}
     * @memberof VisorBindingsApiVisorBindMachineAgent
     */
    readonly id: string

    /**
     * 
     * @type {VisorBindAgentRequest}
     * @memberof VisorBindingsApiVisorBindMachineAgent
     */
    readonly visorBindAgentRequest: VisorBindAgentRequest
}

/**
 * Request parameters for visorGetMachineAgentBinding operation in VisorBindingsApi.
 * @export
 * @interface VisorBindingsApiVisorGetMachineAgentBindingRequest
 */
export interface VisorBindingsApiVisorGetMachineAgentBindingRequest {
    /**
     * 
     * @type {string}
     * @memberof VisorBindingsApiVisorGetMachineAgentBinding
     */
    readonly id: string
}

/**
 * Request parameters for visorUnbindMachineAgent operation in VisorBindingsApi.
 * @export
 * @interface VisorBindingsApiVisorUnbindMachineAgentRequest
 */
export interface VisorBindingsApiVisorUnbindMachineAgentRequest {
    /**
     * 
     * @type {string}
     * @memberof VisorBindingsApiVisorUnbindMachineAgent
     */
    readonly id: string
}

/**
 * VisorBindingsApi - object-oriented interface
 * @export
 * @class VisorBindingsApi
 * @extends {BaseAPI}
 */
export class VisorBindingsApi extends BaseAPI {
    /**
     * 
     * @summary Bind a cloud Agent to a machine
     * @param {VisorBindingsApiVisorBindMachineAgentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VisorBindingsApi
     */
    public visorBindMachineAgent(requestParameters: VisorBindingsApiVisorBindMachineAgentRequest, options?: RawAxiosRequestConfig) {
        return VisorBindingsApiFp(this.configuration).visorBindMachineAgent(requestParameters.id, requestParameters.visorBindAgentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a machine\'s agent binding
     * @param {VisorBindingsApiVisorGetMachineAgentBindingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VisorBindingsApi
     */
    public visorGetMachineAgentBinding(requestParameters: VisorBindingsApiVisorGetMachineAgentBindingRequest, options?: RawAxiosRequestConfig) {
        return VisorBindingsApiFp(this.configuration).visorGetMachineAgentBinding(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List the org\'s agent bindings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VisorBindingsApi
     */
    public visorListAgentBindings(options?: RawAxiosRequestConfig) {
        return VisorBindingsApiFp(this.configuration).visorListAgentBindings(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Unbind the agent from a machine
     * @param {VisorBindingsApiVisorUnbindMachineAgentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VisorBindingsApi
     */
    public visorUnbindMachineAgent(requestParameters: VisorBindingsApiVisorUnbindMachineAgentRequest, options?: RawAxiosRequestConfig) {
        return VisorBindingsApiFp(this.configuration).visorUnbindMachineAgent(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}

