/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud\'s own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdminO11yTotals
 */
export interface AdminO11yTotals {
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'requests'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'tokens'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'promptTokens'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'completionTokens'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'costCents'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'errors'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'orgs'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'models'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'traceCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'latencyP50Ms'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'latencyP95Ms'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'latencyP99Ms'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'traceErrorRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'services'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminO11yTotals
     */
    'logVolume'?: number;
}

