/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgentResourceUsage } from './agent-resource-usage';
// May contain unused imports in some cases
// @ts-ignore
import type { AgentSeriesLine } from './agent-series-line';

/**
 * 
 * @export
 * @interface AgentMetricsView
 */
export interface AgentMetricsView {
    /**
     * echoes the requested window (24H|7D|30D)
     * @type {string}
     * @memberof AgentMetricsView
     */
    'range'?: string;
    /**
     * Resource is the Resource Usage panel\'s rollup, and every field of it is currently null — see resourceUsage. It is present rather than omitted so a panel renders \"—\" instead of guessing.
     * @type {AgentResourceUsage}
     * @memberof AgentMetricsView
     */
    'resource'?: AgentResourceUsage;
    /**
     * per-agent invocation histogram (real)
     * @type {Array<AgentSeriesLine>}
     * @memberof AgentMetricsView
     */
    'series'?: Array<AgentSeriesLine>;
}

