/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ByoGPU
 */
export interface ByoGPU {
    /**
     * native target, e.g. \"gfx1151\"
     * @type {string}
     * @memberof ByoGPU
     */
    'arch'?: string;
    /**
     * VRAM (or unified pool), e.g. \"122880 MiB\"
     * @type {string}
     * @memberof ByoGPU
     */
    'memoryTotal'?: string;
    /**
     * 
     * @type {string}
     * @memberof ByoGPU
     */
    'name'?: string;
    /**
     * unified CPU/GPU memory pool (APU / SoC)
     * @type {boolean}
     * @memberof ByoGPU
     */
    'unified'?: boolean;
}

