/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChannelChannelAgents
 */
export interface ChannelChannelAgents {
    /**
     * Channel is the transport these bindings are for.
     * @type {string}
     * @memberof ChannelChannelAgents
     */
    'channel'?: string;
    /**
     * Default is the agent that answers any room without a binding of its own; \"hanzo\" when the org has never set one.
     * @type {string}
     * @memberof ChannelChannelAgents
     */
    'default'?: string;
    /**
     * Rooms maps a platform room id to the agent that answers there.
     * @type {{ [key: string]: string; }}
     * @memberof ChannelChannelAgents
     */
    'rooms'?: { [key: string]: string; };
}

