/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud\'s own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CloudVoucher } from './cloud-voucher';

/**
 * 
 * @export
 * @interface CloudBookRequest
 */
export interface CloudBookRequest {
    /**
     * Override books this bill even when one of the SAME economic identity (vendor, total, issue date) already posted — the explicit human confirmation that a same-looking bill is a genuine second spend, not the same receipt re-scanned.
     * @type {boolean}
     * @memberof CloudBookRequest
     */
    'override'?: boolean;
    /**
     * ScanID is the scanned document\'s file hash, as GET /v1/books/inbox and the scan draft report it. It is the idempotency key: re-booking the same scan writes nothing.
     * @type {string}
     * @memberof CloudBookRequest
     */
    'scanId'?: string;
    /**
     * Voucher is the reviewed voucher to post. Its source is FORCED to (scan, scanId) server-side, so it can never be booked under another source\'s key.
     * @type {CloudVoucher}
     * @memberof CloudBookRequest
     */
    'voucher'?: CloudVoucher;
}

