/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud\'s own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CloudJourneyStep } from './cloud-journey-step';
// May contain unused imports in some cases
// @ts-ignore
import type { CloudPrinciple } from './cloud-principle';
// May contain unused imports in some cases
// @ts-ignore
import type { CloudSection } from './cloud-section';
// May contain unused imports in some cases
// @ts-ignore
import type { CloudStrategy } from './cloud-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { CloudTemplate } from './cloud-template';

/**
 * 
 * @export
 * @interface CloudBlueprint
 */
export interface CloudBlueprint {
    /**
     * 
     * @type {string}
     * @memberof CloudBlueprint
     */
    'brand'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CloudBlueprint
     */
    'enabled'?: boolean;
    /**
     * the 64-principle spine (Zen of Hanzo archetypes)
     * @type {Array<CloudPrinciple>}
     * @memberof CloudBlueprint
     */
    'principles'?: Array<CloudPrinciple>;
    /**
     * 
     * @type {Array<CloudSection>}
     * @memberof CloudBlueprint
     */
    'sections'?: Array<CloudSection>;
    /**
     * 
     * @type {Array<CloudJourneyStep>}
     * @memberof CloudBlueprint
     */
    'steps'?: Array<CloudJourneyStep>;
    /**
     * 
     * @type {Array<CloudStrategy>}
     * @memberof CloudBlueprint
     */
    'strategies'?: Array<CloudStrategy>;
    /**
     * 
     * @type {Array<CloudTemplate>}
     * @memberof CloudBlueprint
     */
    'templates'?: Array<CloudTemplate>;
    /**
     * 
     * @type {string}
     * @memberof CloudBlueprint
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CloudBlueprint
     */
    'version'?: string;
}

