/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommerceLineItem
 */
export interface CommerceLineItem {
    /**
     * 
     * @type {string}
     * @memberof CommerceLineItem
     */
    'productId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommerceLineItem
     */
    'productName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommerceLineItem
     */
    'productSlug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommerceLineItem
     */
    'productSKU'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommerceLineItem
     */
    'variantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommerceLineItem
     */
    'variantName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommerceLineItem
     */
    'variantSKU'?: string;
    /**
     * 
     * @type {number}
     * @memberof CommerceLineItem
     */
    'quantity'?: number;
    /**
     * Price in cents
     * @type {number}
     * @memberof CommerceLineItem
     */
    'price'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CommerceLineItem
     */
    'taxable'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CommerceLineItem
     */
    'free'?: boolean;
}

