/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateAgentIn
 */
export interface CreateAgentIn {
    /**
     * ComputeRef optionally binds this bot to a visor machine. Opaque here, bounded at 256 characters, and not resolved — this package stores the reference and the binding\'s lifecycle belongs elsewhere.
     * @type {string}
     * @memberof CreateAgentIn
     */
    'computeRef'?: string;
    /**
     * Description is the one line published as the description of the `agent_<name>` tool, which is how another agent decides whether to call this one. Optional, and worth writing for exactly that reason.
     * @type {string}
     * @memberof CreateAgentIn
     */
    'description'?: string;
    /**
     * ExecutionMode is one-shot or long-running. Empty takes one-shot, which runs only when something POSTs to it. long-running additionally requires Schedule, and counts against a per-org cap that answers 409 when it is full.
     * @type {string}
     * @memberof CreateAgentIn
     */
    'executionMode'?: string;
    /**
     * Instructions is the system prompt, up to 32 KiB, stored verbatim. This is what the model reads; Description is what other CALLERS read.
     * @type {string}
     * @memberof CreateAgentIn
     */
    'instructions'?: string;
    /**
     * Model names the model to run on. Omit it to take the deployment\'s configured default; name one and it is checked against the gateway\'s served catalogue here, so a model this deployment cannot serve is refused now rather than at the first run. Stored under our own name for it, whatever spelling arrives.
     * @type {string}
     * @memberof CreateAgentIn
     */
    'model'?: string;
    /**
     * Name is the agent\'s org-unique handle and the only required field. It must match ^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$, and a name already taken in this org is a 409 rather than an overwrite. It is permanent: no update route moves it.
     * @type {string}
     * @memberof CreateAgentIn
     */
    'name'?: string;
    /**
     * Schedule is the 5-field cron a long-running agent fires on, parsed here so a bad expression is a 400 and not an agent that silently never runs. Required with long-running; DISCARDED for one-shot rather than stored unused.
     * @type {string}
     * @memberof CreateAgentIn
     */
    'schedule'?: string;
    /**
     * ServiceAccountID optionally names the IAM agent service account (<org>-<agent>) a scheduled run should be billed AS, so an autonomous run is attributable to a principal rather than only to the org. Same 256-character bound, also unresolved here.
     * @type {string}
     * @memberof CreateAgentIn
     */
    'serviceAccountId'?: string;
    /**
     * Tools are the tool names this agent may call. Omitted or empty grants NONE — that default is the agent\'s authority and is not widened anywhere. The single entry \"*\" means whatever the fleet\'s tool door serves at the time of each run.
     * @type {Array<string>}
     * @memberof CreateAgentIn
     */
    'tools'?: Array<string>;
}

