/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreditGrant } from './credit-grant';

/**
 * 
 * @export
 * @interface CreditGrants
 */
export interface CreditGrants {
    /**
     * 
     * @type {number}
     * @memberof CreditGrants
     */
    'count'?: number;
    /**
     * 
     * @type {Array<CreditGrant>}
     * @memberof CreditGrants
     */
    'grants'?: Array<CreditGrant>;
}

