/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Enrolment
 */
export interface Enrolment {
    /**
     * Created reports whether this call enrolled the org (201) or found an existing enrolment (200).
     * @type {boolean}
     * @memberof Enrolment
     */
    'created'?: boolean;
    /**
     * GithubLogin is the linked forge account.
     * @type {string}
     * @memberof Enrolment
     */
    'githubLogin'?: string;
    /**
     * ID is the author record\'s server-minted handle, \"aut_\"-prefixed.
     * @type {string}
     * @memberof Enrolment
     */
    'id'?: string;
    /**
     * ShareBps is this author\'s royalty share in basis points of the spend their deployed work generates.
     * @type {number}
     * @memberof Enrolment
     */
    'shareBps'?: number;
    /**
     * Status is connected, approved or suspended. Only an approved author earns.
     * @type {string}
     * @memberof Enrolment
     */
    'status'?: string;
    /**
     * Verified reports whether any repository or owner claim has been proven yet.
     * @type {boolean}
     * @memberof Enrolment
     */
    'verified'?: boolean;
    /**
     * VerifyCode is this author\'s stable proof token — the value a repository\'s verify file must carry.
     * @type {string}
     * @memberof Enrolment
     */
    'verifyCode'?: string;
    /**
     * VerifyFile is the repo-root file the file method reads, on the default branch.
     * @type {string}
     * @memberof Enrolment
     */
    'verifyFile'?: string;
    /**
     * VerifySnippet is that file\'s exact contents, ready to commit.
     * @type {string}
     * @memberof Enrolment
     */
    'verifySnippet'?: string;
}

