/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EvaluateIn
 */
export interface EvaluateIn {
    /**
     * DistinctID is the identity the flags are evaluated for. Required.
     * @type {string}
     * @memberof EvaluateIn
     */
    'distinct_id'?: string;
    /**
     * 
     * @type {any}
     * @memberof EvaluateIn
     */
    'groups'?: any;
    /**
     * 
     * @type {any}
     * @memberof EvaluateIn
     */
    'person_properties'?: any;
}

