/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EventModelRow
 */
export interface EventModelRow {
    /**
     * Model is the model id, e.g. zen5-coder.
     * @type {string}
     * @memberof EventModelRow
     */
    'model'?: string;
    /**
     * Pct is this model\'s share of the window\'s returned spend, 0..100, one decimal.
     * @type {number}
     * @memberof EventModelRow
     */
    'pct'?: number;
    /**
     * Provider is who served it.
     * @type {string}
     * @memberof EventModelRow
     */
    'provider'?: string;
    /**
     * Requests is how many calls went to this model.
     * @type {number}
     * @memberof EventModelRow
     */
    'requests'?: number;
    /**
     * SpendCents is what they cost, in cents.
     * @type {number}
     * @memberof EventModelRow
     */
    'spendCents'?: number;
    /**
     * Tokens is prompt plus completion tokens over those calls.
     * @type {number}
     * @memberof EventModelRow
     */
    'tokens'?: number;
}

