/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Execution
 */
export interface Execution {
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'actor'?: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'branch'?: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'conclusion'?: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'endedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'event'?: string;
    /**
     * 
     * @type {number}
     * @memberof Execution
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof Execution
     */
    'number'?: number;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'org'?: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'repo'?: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'sha'?: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'startedAt'?: string;
    /**
     * Status and Conclusion are BOTH required to know how a run went, and reading only one is wrong in a way that looks fine. Status answers \"is it over\" (queued | in_progress | completed); Conclusion answers \"how did it end\" and is empty until it is over. A view that buckets on Status alone sees `completed` and cannot tell a pass from a failure, so it draws every finished run — successes and cancellations included — the same way.
     * @type {string}
     * @memberof Execution
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    'workflow'?: string;
}

