/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FunctionInvocationView } from './function-invocation-view';
// May contain unused imports in some cases
// @ts-ignore
import type { FunctionTriggerView } from './function-trigger-view';

/**
 * 
 * @export
 * @interface FunctionFunctionDetail
 */
export interface FunctionFunctionDetail {
    /**
     * 
     * @type {number}
     * @memberof FunctionFunctionDetail
     */
    'avgDurationMs'?: number;
    /**
     * 
     * @type {string}
     * @memberof FunctionFunctionDetail
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionFunctionDetail
     */
    'endpoint'?: string;
    /**
     * 
     * @type {number}
     * @memberof FunctionFunctionDetail
     */
    'envCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof FunctionFunctionDetail
     */
    'environment'?: string;
    /**
     * 
     * @type {number}
     * @memberof FunctionFunctionDetail
     */
    'errors7d'?: number;
    /**
     * 
     * @type {string}
     * @memberof FunctionFunctionDetail
     */
    'image'?: string;
    /**
     * 
     * @type {number}
     * @memberof FunctionFunctionDetail
     */
    'invocations7d'?: number;
    /**
     * 
     * @type {string}
     * @memberof FunctionFunctionDetail
     */
    'lastDeployedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionFunctionDetail
     */
    'memoryLimit'?: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionFunctionDetail
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionFunctionDetail
     */
    'namespace'?: string;
    /**
     * RecentInvocations is its twenty most recent runs, newest first.
     * @type {Array<FunctionInvocationView>}
     * @memberof FunctionFunctionDetail
     */
    'recentInvocations'?: Array<FunctionInvocationView>;
    /**
     * Secrets are the NAMES it mounts. Values are never read or returned.
     * @type {Array<string>}
     * @memberof FunctionFunctionDetail
     */
    'secrets'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof FunctionFunctionDetail
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof FunctionFunctionDetail
     */
    'successRate'?: number;
    /**
     * 
     * @type {string}
     * @memberof FunctionFunctionDetail
     */
    'target'?: string;
    /**
     * 
     * @type {number}
     * @memberof FunctionFunctionDetail
     */
    'timeoutSec'?: number;
    /**
     * Triggers is how this function is reached.
     * @type {Array<FunctionTriggerView>}
     * @memberof FunctionFunctionDetail
     */
    'triggers'?: Array<FunctionTriggerView>;
}

