/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IamControllersResponse
 */
export interface IamControllersResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof IamControllersResponse
     */
    'data'?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof IamControllersResponse
     */
    'data2'?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof IamControllersResponse
     */
    'data3'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof IamControllersResponse
     */
    'msg'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamControllersResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamControllersResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamControllersResponse
     */
    'sub'?: string;
}

