/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IamCert
 */
export interface IamCert {
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'accessKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'accessSecret'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'account'?: string;
    /**
     * 
     * @type {number}
     * @memberof IamCert
     */
    'bitSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'certificate'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'createdTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'cryptoAlgorithm'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IamCert
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'domainExpireTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof IamCert
     */
    'expireInYears'?: number;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'expireTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'owner'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'provider'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'scope'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof IamCert
     */
    'updatedAt'?: string;
}

