/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IndexTask
 */
export interface IndexTask {
    /**
     * EnqueuedAt, StartedAt and FinishedAt are the same instant: the write was applied before its task id was minted.
     * @type {string}
     * @memberof IndexTask
     */
    'enqueuedAt'?: string;
    /**
     * FinishedAt is when the write completed.
     * @type {string}
     * @memberof IndexTask
     */
    'finishedAt'?: string;
    /**
     * StartedAt is when the write began.
     * @type {string}
     * @memberof IndexTask
     */
    'startedAt'?: string;
    /**
     * Status is always `succeeded`.
     * @type {string}
     * @memberof IndexTask
     */
    'status'?: string;
    /**
     * Type names the kind of write, for a client that inspects it.
     * @type {string}
     * @memberof IndexTask
     */
    'type'?: string;
    /**
     * UID echoes the task id that was asked about.
     * @type {number}
     * @memberof IndexTask
     */
    'uid'?: number;
}

