/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KmsOrganization
 */
export interface KmsOrganization {
    /**
     * 
     * @type {string}
     * @memberof KmsOrganization
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof KmsOrganization
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof KmsOrganization
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof KmsOrganization
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof KmsOrganization
     */
    'updatedAt'?: string;
}

