/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LeaderboardActivityPoint } from './leaderboard-activity-point';
// May contain unused imports in some cases
// @ts-ignore
import type { LeaderboardActivityTotals } from './leaderboard-activity-totals';

/**
 * 
 * @export
 * @interface LeaderboardActivityView
 */
export interface LeaderboardActivityView {
    /**
     * Available is false when nothing could be read: the warehouse is not connected, the rollup is not ready, or the subject is one the ledger cannot attribute (see Note). Days is then empty because there is no answer, not because there was no activity.
     * @type {boolean}
     * @memberof LeaderboardActivityView
     */
    'available'?: boolean;
    /**
     * Days is the gap-filled series, one point per calendar day from From up to (not including) To, in ascending order, zero-valued days included. Always a list, never null.
     * @type {Array<LeaderboardActivityPoint>}
     * @memberof LeaderboardActivityView
     */
    'days'?: Array<LeaderboardActivityPoint>;
    /**
     * From is the first day in Days, \"2006-01-02\" inclusive.
     * @type {string}
     * @memberof LeaderboardActivityView
     */
    'from'?: string;
    /**
     * ID is the subject the server actually read, after resolving \"me\"/empty to the caller and bounding it to what they may see — a ledger \"owner/name\" for a user, an org id for an org. Echoed so a client can confirm whose series it holds.
     * @type {string}
     * @memberof LeaderboardActivityView
     */
    'id'?: string;
    /**
     * Note explains an empty-but-not-broken answer in plain words — today only subject=project, which the usage ledger records no column for. Present only when there is something to say; show it instead of an empty chart.
     * @type {string}
     * @memberof LeaderboardActivityView
     */
    'note'?: string;
    /**
     * Source names the table the series was aggregated from (the derived daily rollup, hanzo.usage_rollup_daily).
     * @type {string}
     * @memberof LeaderboardActivityView
     */
    'source'?: string;
    /**
     * Subject echoes what the series is about: user|org|project.
     * @type {string}
     * @memberof LeaderboardActivityView
     */
    'subject'?: string;
    /**
     * To is the EXCLUSIVE upper bound, \"2006-01-02\" — the day AFTER the last point in Days. A request for to=2026-03-31 answers to=2026-04-01 with 2026-03-31 last.
     * @type {string}
     * @memberof LeaderboardActivityView
     */
    'to'?: string;
    /**
     * Totals are the window\'s sums plus the busiest-day ceilings a heatmap scales against. Derived from Days — nothing here is read separately.
     * @type {LeaderboardActivityTotals}
     * @memberof LeaderboardActivityView
     */
    'totals'?: LeaderboardActivityTotals;
}

