/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MarketMarket } from './market-market';
// May contain unused imports in some cases
// @ts-ignore
import type { MarketReach } from './market-reach';

/**
 * 
 * @export
 * @interface MarketRoster
 */
export interface MarketRoster {
    /**
     * Chains is `[]` where the registry answered and named none, and `null` where it did not answer — never absent, because a missing key and an empty list read alike and only one of them means \"there are none\". Each row carries its OWN reach for its figures, so a chain whose indexer is down is one row saying so.
     * @type {Array<MarketMarket>}
     * @memberof MarketRoster
     */
    'chains'?: Array<MarketMarket>;
    /**
     * Reach is how far the read of the REGISTRY got. It governs the list: a registry that did not answer yields no rows, and the reason it did not is here rather than in an empty array a caller would read as \"no chains exist\".
     * @type {MarketReach}
     * @memberof MarketRoster
     */
    'reach'?: MarketReach;
}

