/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { O11yNodeListRecord } from './o11y-node-list-record';

/**
 * 
 * @export
 * @interface O11yNodeListResponse
 */
export interface O11yNodeListResponse {
    /**
     * 
     * @type {Array<O11yNodeListRecord>}
     * @memberof O11yNodeListResponse
     */
    'records'?: Array<O11yNodeListRecord>;
    /**
     * 
     * @type {number}
     * @memberof O11yNodeListResponse
     */
    'total'?: number;
    /**
     * 
     * @type {string}
     * @memberof O11yNodeListResponse
     */
    'type'?: string;
}

