/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { O11yO11ySpanPercentile } from './o11y-o11y-span-percentile';

/**
 * 
 * @export
 * @interface O11yO11ySpanPercentileOut
 */
export interface O11yO11ySpanPercentileOut {
    /**
     * Data is the placement.
     * @type {O11yO11ySpanPercentile}
     * @memberof O11yO11ySpanPercentileOut
     */
    'data'?: O11yO11ySpanPercentile;
    /**
     * Status is \"success\".
     * @type {string}
     * @memberof O11yO11ySpanPercentileOut
     */
    'status'?: string;
}

