/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OperativeCreateSessionRequest
 */
export interface OperativeCreateSessionRequest {
    /**
     * API provider to use
     * @type {string}
     * @memberof OperativeCreateSessionRequest
     */
    'provider': OperativeCreateSessionRequestProviderEnum;
    /**
     * Model name (defaults to provider default)
     * @type {string}
     * @memberof OperativeCreateSessionRequest
     */
    'model'?: string;
    /**
     * API key for the provider (if not set via env)
     * @type {string}
     * @memberof OperativeCreateSessionRequest
     */
    'apiKey'?: string;
    /**
     * Extra instructions appended to the system prompt
     * @type {string}
     * @memberof OperativeCreateSessionRequest
     */
    'systemPromptSuffix'?: string;
    /**
     * Tool version to use
     * @type {string}
     * @memberof OperativeCreateSessionRequest
     */
    'toolVersion'?: OperativeCreateSessionRequestToolVersionEnum;
    /**
     * Maximum output tokens
     * @type {number}
     * @memberof OperativeCreateSessionRequest
     */
    'maxTokens'?: number;
    /**
     * Token budget for thinking (null to disable)
     * @type {number}
     * @memberof OperativeCreateSessionRequest
     */
    'thinkingBudget'?: number;
    /**
     * Number of recent screenshots to send to model
     * @type {number}
     * @memberof OperativeCreateSessionRequest
     */
    'onlyNMostRecentImages'?: number;
    /**
     * Enable token-efficient tools beta flag
     * @type {boolean}
     * @memberof OperativeCreateSessionRequest
     */
    'tokenEfficientToolsBeta'?: boolean;
    /**
     * Virtual display width in pixels
     * @type {number}
     * @memberof OperativeCreateSessionRequest
     */
    'displayWidth'?: number;
    /**
     * Virtual display height in pixels
     * @type {number}
     * @memberof OperativeCreateSessionRequest
     */
    'displayHeight'?: number;
}

export const OperativeCreateSessionRequestProviderEnum = {
    Anthropic: 'anthropic',
    Bedrock: 'bedrock',
    Vertex: 'vertex'
} as const;

export type OperativeCreateSessionRequestProviderEnum = typeof OperativeCreateSessionRequestProviderEnum[keyof typeof OperativeCreateSessionRequestProviderEnum];
export const OperativeCreateSessionRequestToolVersionEnum = {
    ComputerUse20241022: 'computer_use_20241022',
    ComputerUse20250124: 'computer_use_20250124'
} as const;

export type OperativeCreateSessionRequestToolVersionEnum = typeof OperativeCreateSessionRequestToolVersionEnum[keyof typeof OperativeCreateSessionRequestToolVersionEnum];


