/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Precompile
 */
export interface Precompile {
    /**
     * 
     * @type {string}
     * @memberof Precompile
     */
    'at'?: string;
    /**
     * Code is whether the address carries any. False is an ANSWER — the node replied and there is nothing deployed there — and is not the same as the read having failed, which the enclosing Reach reports instead.
     * @type {boolean}
     * @memberof Precompile
     */
    'code'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Precompile
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Precompile
     */
    'role'?: string;
}

