/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PricingModelList
 */
export interface PricingModelList {
    /**
     * Models are the catalog entries visible to the caller, each an opaque object exactly as the pricing source emits it, with any admin override merged on top. An admin additionally sees hidden entries, each annotated under \"_overlay\".
     * @type {Array<{ [key: string]: object; }>}
     * @memberof PricingModelList
     */
    'models'?: Array<{ [key: string]: object; }>;
    /**
     * Total is how many models this answer carries — recounted over the visible set, not the catalog\'s own total.
     * @type {number}
     * @memberof PricingModelList
     */
    'total'?: number;
    /**
     * Updated is when the catalog was last refreshed, as the pricing source recorded it.
     * @type {object}
     * @memberof PricingModelList
     */
    'updated'?: object;
}

