/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProviderSlackSearchHit
 */
export interface ProviderSlackSearchHit {
    /**
     * Channel is the conversation ID the match sits in.
     * @type {string}
     * @memberof ProviderSlackSearchHit
     */
    'channel'?: string;
    /**
     * ChannelName is that conversation\'s name, when Slack reports one.
     * @type {string}
     * @memberof ProviderSlackSearchHit
     */
    'channel_name'?: string;
    /**
     * Permalink addresses the message in a browser.
     * @type {string}
     * @memberof ProviderSlackSearchHit
     */
    'permalink'?: string;
    /**
     * Text is the matching message\'s text.
     * @type {string}
     * @memberof ProviderSlackSearchHit
     */
    'text'?: string;
    /**
     * TS is the message\'s exact Slack timestamp, the handle for replying to or reacting to it.
     * @type {string}
     * @memberof ProviderSlackSearchHit
     */
    'ts'?: string;
    /**
     * User is the author\'s Slack user ID.
     * @type {string}
     * @memberof ProviderSlackSearchHit
     */
    'user'?: string;
    /**
     * Username is the author\'s display name, when Slack reports one.
     * @type {string}
     * @memberof ProviderSlackSearchHit
     */
    'username'?: string;
}

