/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Registration } from './registration';

/**
 * 
 * @export
 * @interface RegisterPage
 */
export interface RegisterPage {
    /**
     * Count is how many rows this page holds.
     * @type {number}
     * @memberof RegisterPage
     */
    'count'?: number;
    /**
     * Formations are the rows, newest activity first.
     * @type {Array<Registration>}
     * @memberof RegisterPage
     */
    'formations'?: Array<Registration>;
    /**
     * Limit is the page size that was applied.
     * @type {number}
     * @memberof RegisterPage
     */
    'limit'?: number;
    /**
     * Offset is the offset that was applied.
     * @type {number}
     * @memberof RegisterPage
     */
    'offset'?: number;
}

