/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoundInput
 */
export interface RoundInput {
    /**
     * Name is the round\'s name on the cap table, e.g. \"Seed\". Required.
     * @type {string}
     * @memberof RoundInput
     */
    'name'?: string;
    /**
     * PreMoneyValuation is the valuation the round prices off, before the new money.
     * @type {number}
     * @memberof RoundInput
     */
    'preMoneyValuation'?: number;
    /**
     * PricePerShare is the per-share price of a priced round.
     * @type {number}
     * @memberof RoundInput
     */
    'pricePerShare'?: number;
    /**
     * RoundType is PRICED, SAFE or CONVERTIBLE_NOTE. Defaults to PRICED.
     * @type {string}
     * @memberof RoundInput
     */
    'roundType'?: string;
    /**
     * ShareClassID is the cap table\'s share class the round issues into.
     * @type {string}
     * @memberof RoundInput
     */
    'shareClassId'?: string;
    /**
     * TargetAmount is the amount the round is raising, recorded verbatim on the canonical cap table\'s rounds.create contract.
     * @type {number}
     * @memberof RoundInput
     */
    'targetAmount'?: number;
}

