/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud — Unified API
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml, not this file.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StreamProduceRequestRecordsInner
 */
export interface StreamProduceRequestRecordsInner {
    /**
     * Optional partition key
     * @type {string}
     * @memberof StreamProduceRequestRecordsInner
     */
    'key'?: string;
    /**
     * Message value
     * @type {string}
     * @memberof StreamProduceRequestRecordsInner
     */
    'value'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof StreamProduceRequestRecordsInner
     */
    'headers'?: { [key: string]: string; };
    /**
     * Target partition (optional, auto-assigned if omitted)
     * @type {number}
     * @memberof StreamProduceRequestRecordsInner
     */
    'partition'?: number;
}

